### ISSUE TITLE
JVM memory configuration options do not apply in the docker image

### ISSUE THREAD

**Issue by lphuberdeau** [opendistro/for-elasticsearch-docs#10]
```
    environment:
      - cluster.name=odfe-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.zen.ping.unicast.hosts=odfe-node1
```

The ES_JAVA_OPTS variable is overwritten in /usr/local/bin/docker-entrypoint.sh

The memory configurations are currently taken from /usr/share/elasticsearch/config/jvm.options where it is hardcoded. Changing the memory configuration requires either altering the image or mounting the jvm.options file.

I believe this is more of an issue with the image itself. Which repository would be most suitable?

**Comment by aetter** [comment]
Hi @lphuberdeau, thanks a bunch. This is a great catch and definitely a bug. The team is fixing it now. I'll update here when I know more.

**Comment by itiyamas** [comment]
Hi @lphuberdeau, the repository for constructing docker images is not yet open source. We are working on [this](https://github.com/opendistro-for-elasticsearch/community/issues/11) actively and will update here once it is done.

**Comment by itiyamas** [comment]
Hi @lphuberdeau 
I have updated the docker image to fix this. The ES_JAVA_OPTS were overridden and did not extend the orginal ES_JAVA_OPTS. 

Verified this by running nodes info
`
curl -k https://localhost:9200/_cat/nodes?h=heap* -u admin:admin
183mb 36 495.3mb
`

**Comment by lphuberdeau** [comment]
The newly published images now consider the environment variables as expected.

**Comment by gabrielcalderon** [comment]
@lphuberdeau Is that the one published 7 hours ago in Docker Hub?

**Comment by lphuberdeau** [comment]
The one I tested is a little older than that.

**Comment by gabrielcalderon** [comment]
@lphuberdeau Thanks!
