### ISSUE TITLE
kibana service will not start after fresh install

### ISSUE THREAD

**Issue by agrigas** [opendistro/for-elasticsearch-docs#100]
I am getting "Kibana server is not ready yet" after fresh install of elasticsearch and kibana on a new server.  I did not modify the config files at all.  Elasticsearch installed without issue and I'm getting responses when using the curl commands provided in the documentation.  The kibana service never starts.  I am running this on Ubuntu 18

**Comment by aetter** [comment]
Hi @agrigas, thanks for reporting. Try swapping `elasticsearch.url` (the pre-7.0 value) for `elasticsearch.hosts` (the new value) in `/etc/kibana/kibana.yml`. I've also updated the docs.

**Comment by agrigas** [comment]
The service still is not starting after making the change.  Below is my kibana.yml

`
# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# Description:
# Default Kibana configuration for Open Distro.

#server.host: "0.0.0.0"
#server.name: "rmg-docker"


elasticsearch.hosts: https://localhost:9200
elasticsearch.ssl.verificationMode: none
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]

opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
opendistro_security.readonly_mode.roles: ["kibana_read_only"]

`

**Comment by aetter** [comment]
Gotcha. Can you run `journalctl -u kibana.service`, skip to the end, and post the output? For example, I was running into the following before I changed to `elasticsearch.hosts`:

```
systemd[1]: Started Kibana.
kibana[11833]: {"type":"log","@timestamp":"2019-07-17T18:18:43Z","tags":["fatal","root"],"pid":11833,"message":"{ ValidationError: child \"
kibana[11833]:  FATAL  ValidationError: child "elasticsearch" fails because ["url" is not allowed]
systemd[1]: kibana.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: kibana.service: Failed with result 'exit-code'.
```

**Comment by agrigas** [comment]
Jul 17 15:06:55 rmg-docker systemd[1]: Started Kibana.
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:kibana@undefined","info"],"pid":15950,"state":"green","message":"Status changed from uninitialized to green - Ready","pr
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:elasticsearch@undefined","info"],"pid":15950,"state":"yellow","message":"Status changed from uninitialized to yellow - W
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:opendistro-alerting@1.0.0.0","info"],"pid":15950,"state":"green","message":"Status changed from uninitialized to green -
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:opendistro_security@7.0.1","info"],"pid":15950,"state":"yellow","message":"Status changed from uninitialized to yellow -
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:opendistro_security@7.0.1","info"],"pid":15950,"state":"yellow","message":"Status changed from yellow to yellow - Defaul
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:opendistro_security@7.0.1","info"],"pid":15950,"state":"yellow","message":"Status changed from yellow to yellow - 'opend
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:opendistro_security@7.0.1","info"],"pid":15950,"state":"yellow","message":"Status changed from yellow to yellow - Securi
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:opendistro_security@7.0.1","info"],"pid":15950,"state":"yellow","message":"Status changed from yellow to yellow - Securi
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:opendistro_security@7.0.1","info"],"pid":15950,"state":"yellow","message":"Status changed from yellow to yellow - Securi
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:opendistro_security@7.0.1","info"],"pid":15950,"state":"yellow","message":"Status changed from yellow to yellow - Routes
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:apm_oss@undefined","info"],"pid":15950,"state":"green","message":"Status changed from uninitialized to green - Ready","p
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:console@undefined","info"],"pid":15950,"state":"green","message":"Status changed from uninitialized to green - Ready","p
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:interpreter@undefined","info"],"pid":15950,"state":"green","message":"Status changed from uninitialized to green - Ready
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:metrics@undefined","info"],"pid":15950,"state":"green","message":"Status changed from uninitialized to green - Ready","p
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:tile_map@undefined","info"],"pid":15950,"state":"green","message":"Status changed from uninitialized to green - Ready","
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:timelion@undefined","info"],"pid":15950,"state":"green","message":"Status changed from uninitialized to green - Ready","
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:elasticsearch@undefined","info"],"pid":15950,"state":"green","message":"Status changed from yellow to green - Ready","pr
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:opendistro_security@7.0.1","info"],"pid":15950,"state":"yellow","message":"Status changed from yellow to yellow - Settin
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["status","plugin:opendistro_security@7.0.1","info"],"pid":15950,"state":"green","message":"Status changed from yellow to green - Open Dis
Jul 17 15:06:59 rmg-docker kibana[15950]: {"type":"log","@timestamp":"2019-07-17T19:06:59Z","tags":["listening","info"],"pid":15950,"message":"Server running at http://localhost:5601"}
Jul 17 15:07:06 rmg-docker kibana[15950]: {"type":"response","@timestamp":"2019-07-17T19:07:06Z","tags":[],"pid":15950,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"localhost:5601","user-agent":"curl/
Jul 17 16:23:45 rmg-docker kibana[15950]: {"type":"response","@timestamp":"2019-07-17T20:23:45Z","tags":[],"pid":15950,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"localhost:5601","user-agent":"curl/
lines 197962-198023/198023 (END)

**Comment by aetter** [comment]
That looks like success to me. You've got the critical `Server running at http://localhost:5601` message, and you can even see the responses to your curl requests. If you're struggling to connect using a web browser from your local machine, you have to configure `server.host` and `server.port` so that there's something to connect to -- and you might have to tweak some settings in Ubuntu to allow remote connections -- but those log lines look very hopeful to me.

**Comment by agrigas** [comment]
You are correct.  I modified the server.host entry, and I’m able to connect via a remote machine.  Thanks so much for helping this newbie through this issue!
