### ISSUE TITLE
Incorrect alerting setting

### ISSUE THREAD

**Issue by dbbaughe** [opendistro/for-elasticsearch-docs#102]
Incorrect alerting setting on docs, refer to:
https://github.com/opendistro-for-elasticsearch/alerting/issues/85

**Comment by aetter** [comment]
Hey @dbbaughe, a few questions:

1. Does this mean that alerting plugin can't be disabled independently of any other plugins that use the job scheduler plugin?
1. We're also missing `opendistro.alerting.index_timeout`, `opendistro.alerting.request_timeout`, and `opendistro.scheduled_jobs.request_timeout`. I couldn't find any descriptions when I glanced at the code. Can you clarify their usage?

**Comment by dbbaughe** [comment]
Hey @aetter,

1. Currently alerting uses it's own implementation of job-scheduler. It is not using the standalone version. So yes, those are currently tied together and disabling one disables the other. There is needed work to get it to use the standalone job-scheduler along with some work that needs to be done in job-scheduler before it's even possible.

2. For the other settings:
2.1 `opendistro.alerting.index_timeout`: Seems to be used as the timeout for creating Monitors and Destinations through the APIs.
2.2 `opendistro.alerting.request_timeout`: Seems to be used in the create monitor API when doing a search request to validate if we have reached the max monitors. Also used in the AlertIndices class when attempting to rollover the history alias, uses it as the request timeout for the rollover call.
2.3 `opendistro.scheduled_jobs.request_timeout`: Used as the request_timeout for the request that sweeps the shards for jobs.
