### ISSUE TITLE
Add link to version history from tech docs left hand side nav

### ISSUE THREAD

**Issue by alolita** [opendistro/for-elasticsearch-docs#104]
@aetter requesting a link to be added to the left hand nav for tech docs for community members to find info on Open Distro version history and related changes.

https://opendistro.github.io/for-elasticsearch-docs/#version-history

**Comment by aetter** [comment]
Hi @alolita, sure, I moved version history to its own page: https://github.com/opendistro/for-elasticsearch-docs/commit/98499aaaed85042f06f42d9389f0d5f9d0baa342

Should be live here: https://opendistro.github.io/for-elasticsearch-docs/version-history/
