### ISSUE TITLE
Alerting Acknowledgement for users  

### ISSUE THREAD

**Issue by skirankumar** [opendistro/for-elasticsearch-docs#106]
Hi 
Iam trying to make a user who only can view all the things(Discover tab,dashboard etc) and they should be able to acknowledge the alerts.

what is the preferred settings for creating this user 
My settings were 
![Screenshot from 2019-08-01 19 42 21](https://user-images.githubusercontent.com/18494007/62300648-cbde1700-b494-11e9-84e6-f4a3078be5b7.png)
Help me with right  configuration

**Comment by aetter** [comment]
Hi @skirankumar, you need to provide that role CRUD access to the `.opendistro-alerting-alerts index`: https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/security-roles/#view-and-acknowledge-alerts
