### ISSUE TITLE
Unrecognized field "cluster". Documentation outdate

### ISSUE THREAD

**Issue by r00t9** [opendistro/for-elasticsearch-docs#109]
From this example [roles-example](https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/users-roles/#rolesyml)  they have wrong variables to create the yaml roles 

I tried with "cluster" but i get the error 

> Unrecognized field "cluster" (7 known properties: "index_permissions", "reserved", "hidden", "description", "static", "cluster_permissions", "tenant_permissions"])

**Comment by aetter** [comment]
Thanks a bunch for reporting! Should be fixed.
