### ISSUE TITLE
Add documentation for commercial support

### ISSUE THREAD

**Issue by barryhatfield** [opendistro/for-elasticsearch-docs#11]
Please create a "commercial support" page if someone needs priority help, needs to get up to speed quickly, requires some training or mentoring, or needs full 24 x 7 production support.

Allow companies to post their information on that page. I have a small Elasticsearch and Kafka related consulting company that I would like to add to the page. 

Here is an example: http://camel.apache.org/commercial-camel-offerings.html

**Comment by CarlMeadows** [comment]
Hi Barry - I will send you a message so we can follow-up on email. We absolutely want to support folks offering support services.

**Comment by aetter** [comment]
Closing this out, but I hope you were able to get in touch.
