### ISSUE TITLE
Add a section about plugins

### ISSUE THREAD

**Issue by monolithed** [opendistro/for-elasticsearch-docs#110]
I could not find the Canvas section in my app. Could you please describe how to install that plugin into Kibana?

<img width="1280" alt="Screenshot 2019-08-08 at 19 30 46" src="https://user-images.githubusercontent.com/803674/62720619-0e629f00-ba13-11e9-9871-813e8f998a54.png">

**Comment by aetter** [comment]
Hi @monolithed, Open Distro for Elasticsearch uses the OSS versions of Elasticsearch and Kibana and adds additional open source plugins on top of them. Canvas is governed by the proprietary Elastic license, so it's not a part of ODFE.
