### ISSUE TITLE
Truststore not optional when using ldap authz

### ISSUE THREAD

**Issue by joeryan** [opendistro/for-elasticsearch-docs#112]
The truststore is listed as an alternative to certificates and private keys.  The opendistro_security.ssl.transport.truststore_filepath and/or opendistro_security.http.transport.truststore_filepath appear to be required for authz to function correctly.  I kept getting an Empty file path for opendistro_security.ssl.transport.truststore_filepath error when trying to use ldap for authz even though authc worked correctly.  I'm not sure if this is a documentation issue or implementation issue.  Please advise if it should be added to the issues for the [security plugin](https://github.com/opendistro-for-elasticsearch/security)

- [truststore listed as alternative method in documentation](https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/tls/#keystore-and-truststore-files)
- [forum post on issue with ldap authz and error](https://discuss.opendistrocommunity.dev/t/error-empty-file-path-for-opendistro-security-ssl-transport-truststore-filepath/733)

**Comment by hardik-k-shah** [comment]
I don't think security plugin restrict usage of trust store in case of LDAP. 
Can you provide your configuration and also provide detailed error/stack trace?

**Comment by aetter** [comment]
Closing this out since @ashwinkumar12345 made a very small change to the text. If there's more to do here, please open an issue at https://github.com/opensearch-project/documentation-website/issues.
