### ISSUE TITLE
Possible issue with SAML configuration examples?

### ISSUE THREAD

**Issue by tcrisall** [opendistro/for-elasticsearch-docs#120]
I've been struggling to get the SAML configuration for elasticsearch working with opendistro 1.1.0 deployed in Docker...  I finally managed to squeeze the below error out of my system.  It implies that in the example:
`saml_auth_domain:`
`    enabled: true`
the 'enabled: true' is causing issues...  I don't know if this is a bug in the code or something has changed and the documentation hasn't caught up.

ERR: Seems /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml is not in Open Distro Security 7 format: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "enabled" (class com.amazon.opendistroforelasticsearch.security.securityconf.impl.v7.ConfigV7$AuthcDomain), not marked as ignorable 

(6 known properties: "http_enabled", "transport_enabled", "http_authenticator", "authentication_backend", "order", "description"])
 at [Source: {"_meta":{"type":"config","config_version":2},"config":{"dynamic":{"http":{"anonymous_auth_enabled":false,"xff":{"enabled":false,"internalProxies":"192\\.168\\.0\\.10|192\\.168\\.0\\.11"}},"authc":{"basic_internal_auth_domain":{"description":"Authenticate via HTTP Basic against internal users database","http_enabled":true,"transport_enabled":true,"order":0,"http_authenticator":{"type":"basic","challenge":false},"authentication_backend":{"type":"internal"}},"saml_auth_domain":{"enabled":true,"order":1,

`<snip>` 

}}}}}}; line: 1, column: 496] (through reference chain: com.amazon.opendistroforelasticsearch.security.securityconf.impl.SecurityDynamicConfiguration["config"]->com.amazon.opendistroforelasticsearch.security.securityconf.impl.v7.ConfigV7["dynamic"]->com.amazon.opendistroforelasticsearch.security.securityconf.impl.v7.ConfigV7$Dynamic["authc"]->com.amazon.opendistroforelasticsearch.security.securityconf.impl.v7.ConfigV7$Authc["saml_auth_domain"]->com.amazon.opendistroforelasticsearch.security.securityconf.impl.v7.ConfigV7$AuthcDomain["enabled"])

**Comment by aetter** [comment]
Hi @tcrisall, thanks a bunch for reporting. Try `"http_enabled": true,"transport_enabled": true,"` in place of just `"enabled": true`. If that works, let me know and I can update the documentation. External auth sources are notoriously hard to test, so it's very possible that something changed under the hood and we didn't catch it.
