### ISSUE TITLE
[Website] Version is not up-to-date

### ISSUE THREAD

**Issue by gna582** [opendistro/for-elasticsearch-docs#128]
Dear developers,

I would like to report a documentation bug:

The homepage implies that ES 7.0.1 and Opendistro 1.0.2 are the latest versions:
![2019-09-20-091129_555x707_scrot](https://user-images.githubusercontent.com/2534537/65306922-d78db600-db86-11e9-8387-9a1c82be3a2e.png)
https://opendistro.github.io/for-elasticsearch/downloads.html

In the deb install guide the latest version is implied to be ES 7.1.1:
```
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.1.1-amd64.deb
sudo dpkg -i elasticsearch-oss-7.1.1-amd64.deb
```
https://opendistro.github.io/for-elasticsearch-docs/docs/install/deb/

The debian repo tells me that ES 7.2.0 and opendistro 1.2.0 are latest:
```
apt show opendistroforelasticsearch -a
Package: opendistroforelasticsearch
Version: 1.2.0-1
Priority: optional
Section: java
Source: opendistroforelasticsearch
Maintainer: OpenDistro for Elasticsearch Team <opendistro@amazon.com>
Installed-Size: unknown
Depends: elasticsearch-oss (= 7.2.0), opendistro-alerting (>= 1.2.0), opendistro-sql (>= 1.2.0), opendistro-security (>= 1.2.0), opendistro-performance-analyzer (>= 1.2.0), opendistro-job-scheduler (>= 1.2.0), opendistro-alerting (<< 1.2.1), opendistro-sql (<< 1.2.1), opendistro-security (<< 1.2.1), opendistro-performance-analyzer (<< 1.2.1), opendistro-job-scheduler (<< 1.2.1)
Homepage: https://opendistro.github.io/for-elasticsearch/downloads.html
Download-Size: 724 B
APT-Sources: http://reposrv.server.lan/d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages
Description: OpenDistro for Elasticsearch.  Reference documentation can be found at https://opendistro.github.io/for-elasticsearch-docs/.
```

As docker hub's latest version is also 1.2.0 I figure those to be the correct version but I imagine many people will check the website for new versions so they won't know there are more recent versions.

Thank you!

**Comment by aetter** [comment]
Hi @gna582, thanks a bunch for letting us know, and apologies for the mess. I just pushed a change to the main website and fixed the Debian version in the docs. Let me know if you spot anything else.
