### ISSUE TITLE
RPM Install : [Errno 256] No more mirrors to try

### ISSUE THREAD

**Issue by csavengers** [opendistro/for-elasticsearch-docs#135]
Trying other mirror.
opendistroforelasticsearch-art FAILED
https://d3g5vo6xdbdb9a.cloudfront.net/yum/noarch/repodata/primary.sqlite.bz2: [Errno 14] curl#63 - "Callback aborted"0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
https://d3g5vo6xdbdb9a.cloudfront.net/yum/noarch/repodata/primary.sqlite.bz2: [Errno 14] curl#63 - "Callback aborted"
Trying other mirror.

 One of the configured repositories failed (Release RPM artifacts of OpenDistroForElasticsearch),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=opendistroforelasticsearch-artifacts-repo ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable opendistroforelasticsearch-artifacts-repo
        or
            subscription-manager repos --disable=opendistroforelasticsearch-artifacts-repo

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=opendistroforelasticsearch-artifacts-repo.skip_if_unavailable=true

Tried following steps pasted in this link - https://opendistro.github.io/for-elasticsearch-docs/docs/install/rpm/

**Comment by aetter** [comment]
Hi @csavengers I'm not able to reproduce on a new RHEL 8 box. Can you try again and see if the issue persists?

**Comment by csavengers** [comment]
I ran into this error when tried from Amazon Linux 2  ( November patch release )

**Comment by aetter** [comment]
Gotcha, try running `sudo yum update` first. That fixed the problem for me.

**Comment by csavengers** [comment]
it worked on new instance. Had issues running it on existing instance. Thanks for your help :)
