### ISSUE TITLE
API Documentation is outdated

### ISSUE THREAD

**Issue by jjmerchante** [opendistro/for-elasticsearch-docs#139]
Hi,

I am trying to use the Opendistro API

I think all the documentation in https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/document-level-security/ is different to https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/api/

When I try to patch a role, I don't know how to do it in OpenDistro 1.2.0: https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/api/#patch-role, I think this is also outdated.

This is just a request to update the documentation, I don't know if there is another place where it is updated, or maybe I am doing something wrong

Thank you!

**Comment by aetter** [comment]
Hi @jjmerchante, thanks a bunch for the issue. All of the Security plugin APIs changed for 1.0.0, so I must have missed a few. Agreed that the PATCH API is incredibly hard to figure out. I've updated the docs here: https://github.com/opendistro/for-elasticsearch-docs/commit/06443b524878b8e4e45a176821c05cd9aab70674

Please let me know if you spot anything else, and thanks again!
