### ISSUE TITLE
Add documentation for security CLI tools

### ISSUE THREAD

**Issue by elfisher** [opendistro/for-elasticsearch-docs#14]
Add documentation to cover the functionality of the security CLI tools.

**Comment by gatis** [comment]
Nay need to add this or similar example somewhere in visible place (reloading security config after you have changed default passwords in /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml. 
Took me too many trials and errors to call it correctly.

`/usr/share/elasticsearch/plugins/opendistro_security/tools/securityadmin.sh -cacert /etc/elasticsearch/root-ca.pem -cert /etc/elasticsearch/kirk.pem -key /etc/elasticsearch/kirk-key.pem  -cd /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/`

**Comment by reilee** [comment]
Looks like we can take reference from search guard doc:
https://docs.search-guard.com/latest/sgadmin
Not sure if any difference but it works perfect for me.

**Comment by aetter** [comment]
Related: https://github.com/opendistro-for-elasticsearch/security-advanced-modules/issues/3

**Comment by aetter** [comment]
https://github.com/opendistro/for-elasticsearch-docs/commit/c1fad0646b539cddec7593d55685e7931ef5ee06
