### ISSUE TITLE
Timelion not available

### ISSUE THREAD

**Issue by BornTKill** [opendistro/for-elasticsearch-docs#144]
Dear All,

I ve deployed Kibana-oss with security and alerting plugins thanks to puppet. Everything is Ok 👍🏻 Great job to the contributors !
Is it possible to have timelion with this setup ? (I ve also try with apt install opendistroforelasticsearch-kibana (instead of oss + plugin) but it makes no difference.

Thank you for the clarification.

**Comment by aetter** [comment]
Hey @BornTKill, Timelion changed in Kibana 7.0. You should see it as one of the options if you create a new visualization. If you want the navigation icon on the left back, add `timelion.ui.enabled: true` to `kibana.yml`.
