### ISSUE TITLE
Indicate Anomaly Detection plugins are in-development and not bundled with Open Distro

### ISSUE THREAD

**Issue by alolita** [opendistro/for-elasticsearch-docs#148]
Please indicate clearly that the AD plugins are in-development and in-flux. It may be confusing for the user to assume that these plugins are fully functional currently. 

https://opendistro.github.io/for-elasticsearch-docs/docs/ad/
https://opendistro.github.io/for-elasticsearch-docs/docs/ad/api/

**Comment by aetter** [comment]
@ashwinkumar12345

**Comment by aetter** [comment]
https://github.com/opendistro/for-elasticsearch-docs/commit/d98ac10d8888df401875d2b571229b05d7756f97
