### ISSUE TITLE
Kibana DSL Query

### ISSUE THREAD

**Issue by Haddad1** [opendistro/for-elasticsearch-docs#151]
So im trying to make a monitor on Alerts for Kibana OSS but im not sure how to search through the data/logs that i have using the extraction query. This is an example of one of the hits:

    {
        "_shards": {
            "total": 1,
            "failed": 0,
            "successful": 1,
            "skipped": 0
        },
        "hits": {
            "hits": [
                {
                    "_index": "logstash-2019.12.16",
                    "_type": "_doc",
                    "_source": {
                        "@timestamp": "2019-12-16T00:20:36.854Z",
                        "system": {
                            "filesystem": {
                                "total": 20749807616,
                                "device_name": "/dev/nvme0n1p1",
                                "mount_point": "/",
                                "free_files": 2360019,
                                "available": 14942003200,
                                "files": 2560000,
                                "used": {
                                    "pct": 0.2793,
                                    "bytes": 5791027200
                                },
                                "free": 14958780416,
                                "type": "ext4"
                            }
                        }

what would be the correct syntax to search/filter for "device name" and "pct"? what im trying to do exactly is for every device name if the value of pct is greater than 0.75 then it would alert me.

the documentation on the ELK site is just really hard to understand!

Thank you in advance for any help or guidance.

**Comment by aetter** [comment]
Hi @Haddad1, try just doing your search for all (or narrow it down to some set of documents based on another field). So your extraction query looks like this:

```
{
  "query": {
    "match_all": {}
  }
}
```

Then for your trigger condition, try something like this:

```
for (int i = 0; i < ctx.results[0].hits.hits.length; i++) {
  if (ctx.results[0].hits.hits[i]._source.system.filesystem.used.pct > 0.75) {
    return true
  }
}
```

**Comment by Haddad1** [comment]
Thank you @aetter very much i will give that a try! and another quick question how can i also include a timestamp range, like since im using all the log files and some are obviously older than others i want the monitor to check for the last 5-10mins lets say, how would that incorporate into the query?

Again Thank you very much!

**Comment by Haddad1** [comment]
the issue is that my timestamp includes both date and time so im not sure how i would be able to be that specific, is it even possible?

**Comment by aetter** [comment]
Yeah, definitely. I think you should be fine with a range query (instead of `match_all`). Here's an example that assumes you're using the [ISO standard](https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations) format:

```
{
    "query": {
        "range" : {
            "timestamp" : {
                "gte" : "2019-12-22T04:36:29"
            }
        }
    }
}
```

Looking at your initial question further, I suspect there's a way to do the filtering in a similar way with the query DSL (which presumably has better performance than Painless), and then you can just have the script evaluate whether or not there are any hits (`ctx.results[0].hits.total.value > 0`), but do whatever seems simpler to you. 👍

**Comment by Haddad1** [comment]
You're awesome thank you very much good sir!

**Comment by Haddad1** [comment]
sorry quick question, is there a proper guide that you can share for me to keep as a reference because honestly all the ones that i've found so far are not exactly easy to understand

**Comment by aetter** [comment]
Hi @Haddad1, I suspect you've already found the best resources. [Our docs](https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/monitors/) assume a certain level of familiarity with Elasticsearch. If you don't have that familiarity, the Elastic documentation is the most comprehensive option.
