### ISSUE TITLE
No docs for proxy authentication

### ISSUE THREAD

**Issue by jimmyjones2** [opendistro/for-elasticsearch-docs#164]
Should there be some?

The [sample config](https://github.com/opendistro-for-elasticsearch/security/blob/master/securityconfig/config.yml) contains the relevant fields - config.dynamic.authc.proxy_auth_domain

Searchguard docs apply, see [elasticsearch](https://docs.search-guard.com/latest/proxy-authentication), [kibana](https://docs.search-guard.com/latest/kibana-authentication-proxy). Also opendistro-for-elasticsearch/security#174

**Comment by aetter** [comment]
Hi @jimmyjones2, yep, I'm just waiting for a review on https://github.com/opendistro/for-elasticsearch-docs/pull/152 before merging.

**Comment by jimmyjones2** [comment]
@aetter Thanks! Have left a comment on the PR
