### ISSUE TITLE
Removing security from Kibana instructions do not work

### ISSUE THREAD

**Issue by johntmyers** [opendistro/for-elasticsearch-docs#174]
Per https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/disable/ we're just supposed to create a new Docker image, if you try this Dockerfile:

```
FROM amazon/opendistro-for-elasticsearch-kibana:1.3.0
RUN /usr/share/kibana/bin/kibana-plugin remove opendistro_security
```

Then simply:

```
docker build -t kibana-fail .
```

Then

```
docker run kibana-fail
```

You get this:
```
{"type":"log","@timestamp":"2020-02-01T19:15:04Z","tags":["fatal","root"],"pid":1,"message":"{ Error: \"opendistro_security.multitenancy.enabled\", \"opendistro_security.multitenancy.tenants.preferred\", and \"opendistro_security.readonly_mode.roles\" settings were not applied. Check for spelling errors and ensure that expected plugins are installed.\n    at KbnServer._default (/usr/share/kibana/src/legacy/server/config/complete.js:90:17) code: 'InvalidConfig', processExitCode: 64 }"}

 FATAL  Error: "opendistro_security.multitenancy.enabled", "opendistro_security.multitenancy.tenants.preferred", and "opendistro_security.readonly_mode.roles" settings were not applied. Check for spelling errors and ensure that expected plugins are installed.
```

What is missing?

**Comment by aetter** [comment]
Hi @johntmyers, I believe step 6 on that page should do the trick for you:

Remove all opendistro_security lines from kibana.yml.

**Comment by johntmyers** [comment]
That implies a custom kibana.yml file is required and your docker-compose example does not use that nor do you explicitly mention it is needed. 

Are the default Kibana YAML configs published anywhere so they can be used as a template for the custom config needed for this? I only see the Kibana container available on DockerHub but not a repo that holds the configs.

**Comment by aetter** [comment]
Hi @johntmyers, yep, that's fair. The current content assumes you're using a custom configuration and just indicates how to modify it. Check out https://github.com/opendistro/for-elasticsearch-docs/commit/97911ccea815ad47dd1ec736763f5f457968c8a0 and let me know what you think.

**Comment by johntmyers** [comment]
Just tried it, works!
