### ISSUE TITLE
Elasticsearch service failing post upgrading to 1.3.0

### ISSUE THREAD

**Issue by devildev2018** [opendistro/for-elasticsearch-docs#179]
Hi Team,

I have recently upgraded the opendistroleasticsearch from 1.2.0 to 1.30 and post upgrade the service not getting up and keeps on failing. 
Find the logs below - 

Feb 07 07:44:39 testlogmgr01.netcracker.com elasticsearch[4195]: ^
Feb 07 07:44:39 testlogmgr01.netcracker.com elasticsearch[4195]: expected <block end>, but found Key
Feb 07 07:44:39 testlogmgr01.netcracker.com elasticsearch[4195]: in 'reader', line 118, column 4:
Feb 07 07:44:39 testlogmgr01.netcracker.com elasticsearch[4195]: path.data: /opt/elasticsearch
Feb 07 07:44:39 testlogmgr01.netcracker.com elasticsearch[4195]: ^
Feb 07 07:44:39 testlogmgr01.netcracker.com elasticsearch[4195]: at [Source: sun.nio.ch.ChannelInputStream@5e3f861; line: 117, column: 9]]; nested: ParserException[while parsing a block collection
Feb 07 07:44:39 testlogmgr01.netcracker.com elasticsearch[4195]: in 'reader', line 117, column 4:
Feb 07 07:44:39 testlogmgr01.netcracker.com systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Feb 07 07:44:39 testlogmgr01.netcracker.com systemd[1]: Unit elasticsearch.service entered failed state.
Feb 07 07:44:39 testlogmgr01.netcracker.com systemd[1]: elasticsearch.service failed.

**Comment by aetter** [comment]
Hey @devildev2018, not much to go off of here. Can you provide any obvious exceptions from the end of `elasticsearch.log`?

**Comment by devildev2018** [comment]
Hi @aetter, Thank you so much for the support. I have managed to fix the issue. 
The issue was there in the elasticsearch.yml file which was causing the application not to start. Now my elk stack is up and running.
