### ISSUE TITLE
Wrong security API endpoint in documentation

### ISSUE THREAD

**Issue by dpotapov** [opendistro/for-elasticsearch-docs#182]
This page https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/api/#get-configuration has wrong API endpoint documented. I guess it was changed in recent OpenDistro version - see [OpenDistroSecurityConfigAction.java#L62](https://github.com/opendistro-for-elasticsearch/security/blob/007c9158e6f5e14901c4c04b323633b27944e37b/src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/OpenDistroSecurityConfigAction.java#L62).

Documented endpoint: `GET _opendistro/_security/api/config`
Actual endpoint: `GET _opendistro/_security/api/securityconfig`

Also would be nice to have such changes documented in release notes...

**Comment by aetter** [comment]
Thanks @dpotapov. These sorts of changes often make their way over to the docs, but it looks like this one slipped through. https://github.com/opendistro/for-elasticsearch-docs/commit/efe144310f6e005626a2313550f2e8f33c2019ab
