### ISSUE TITLE
Getting error after installed standlone elasticsearch security plugin

### ISSUE THREAD

**Issue by manalilrafeeq** [opendistro/for-elasticsearch-docs#183]
I am new to opendistro standlone plugins. I tried to customize my ELK stack with opendistro security and alerting plugin. I have successsfully installed the security elastic search plugin  with the provided demo certificates. 

Versions : 

Eleasticsearch - 7.4.2
Kibana - 7.4.2
Opendistro security plugin - 1.4.0.0

After installation, restarted elasticsearch, I am getting an error :

org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:52)
elasticsearch[24567]: at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:645)
Feb 15 20:52:46 elasticsearch[24567]: at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:620)
Feb 15 20:52:46  elasticsearch[24567]: at org.elasticsearch.common.settings.Settings.access$400(Settings.java:82)
Feb 15 20:52:46 elasticsearch[24567]: at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1093)

[2020-02-15T20:37:46,352][INFO ][o.e.n.Node               ] [master] stopping ...
[2020-02-15T20:37:46,385][INFO ][o.e.x.w.WatcherService   ] [master] stopping watch service, reason [shutdown initiated]
[2020-02-15T20:37:46,386][INFO ][o.e.x.w.WatcherLifeCycleService] [master] watcher has stopped and shutdown
[2020-02-15T20:37:46,711][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [master] [controller/11581] [Main.cc@150] Ml controller exiting
[2020-02-15T20:37:46,712][INFO ][o.e.x.m.p.NativeController] [master] Native controller process has stopped - no new native processes can be started
[2020-02-15T20:37:52,246][INFO ][o.e.n.Node               ] [master] stopped
[2020-02-15T20:37:52,246][INFO ][o.e.n.Node               ] [master] closing ...
[2020-02-15T20:37:52,338][INFO ][o.e.n.Node               ] [master] closed
 
while installing, I was getting some warning like below (oracle java) : 

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission createClassLoader
* java.lang.RuntimePermission getClassLoader
* java.net.NetPermission getProxySelector
* java.net.SocketPermission * connect,resolve
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

**Comment by manalilrafeeq** [comment]
more stacktrace on this issue - 

{"type": "server", "timestamp": "2020-02-17T10:14:18,750Z", "level": "INFO", "component": "o.e.x.m.p.l.CppLogMessageHandler", "cluster.name": "idams-nonprod-elk", "node.name": "master", "message": "[controller/33614] [Main.cc@110] controller (64 bit): Version 7.4.2 (Build 473f61b8a5238b) Copyright (c) 2019 Elasticsearch BV" }
{"type": "server", "timestamp": "2020-02-17T10:14:20,994Z", "level": "DEBUG", "component": "o.e.a.ActionModule", "cluster.name": "idams-nonprod-elk", "node.name": "master", "message": "Using REST wrapper from plugin org.elasticsearch.xpack.security.Security" }
{"type": "server", "timestamp": "2020-02-17T10:14:20,995Z", "level": "DEBUG", "component": "o.e.a.ActionModule", "cluster.name": "idams-nonprod-elk", "node.name": "master", "message": "Using REST wrapper from plugin com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin" }
{"type": "server", "timestamp": "2020-02-17T10:14:21,004Z", "level": "ERROR", "component": "o.e.b.Bootstrap", "cluster.name": "idams-nonprod-elk", "node.name": "master", "message": "Exception",
"stacktrace": ["java.lang.IllegalArgumentException: Cannot have more than one plugin implementing a REST wrapper",
"at org.elasticsearch.action.ActionModule.<init>(ActionModule.java:396) ~[elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.node.Node.<init>(Node.java:457) ~[elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.node.Node.<init>(Node.java:255) ~[elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) [elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) [elasticsearch-cli-7.4.2.jar:7.4.2]",
"at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-7.4.2.jar:7.4.2]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) [elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-7.4.2.jar:7.4.2]"] }
{"type": "server", "timestamp": "2020-02-17T10:14:21,028Z", "level": "WARN", "component": "o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name": "idams-nonprod-elk", "node.name": "master", "message": "uncaught exception in thread [main]",
"stacktrace": ["org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Cannot have more than one plugin implementing a REST wrapper",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) ~[elasticsearch-cli-7.4.2.jar:7.4.2]",
"at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.4.2.jar:7.4.2]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.4.2.jar:7.4.2]",
"Caused by: java.lang.IllegalArgumentException: Cannot have more than one plugin implementing a REST wrapper",
"at org.elasticsearch.action.ActionModule.<init>(ActionModule.java:396) ~[elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.node.Node.<init>(Node.java:457) ~[elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.node.Node.<init>(Node.java:255) ~[elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.4.2.jar:7.4.2]",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.4.2.jar:7.4.2]",
"... 6 more"] }


I also tried to disable the xpack in elasticsearch.yml file (xpack.security.enabled: false)

please help me to resolve this issue.

**Comment by aetter** [comment]
Hi @manalilrafeeq, we only test with the Apache 2.0 licensed version of Elasticsearch (often called `elasticsearch-oss` in package managers). It sounds like you're running the "default" version, which includes a few basic security features and other plugins. The line in your logs that's jumping out to me is `Cannot have more than one plugin implementing a REST wrapper`. If you try again on an elasticsearch-oss cluster, I think you'll have better luck.
