### ISSUE TITLE
Shasum for the tarball assumes it resides in a subdirectory

### ISSUE THREAD

**Issue by IsaacHaze** [opendistro/for-elasticsearch-docs#184]
Following the installation steps from the tarball guide (at https://opendistro.github.io/for-elasticsearch-docs/docs/install/tar/) fails at step 3 "verify the tarball against the checksum".

The checksum file seems to assume that the downloaded tarball sits in a `tarfiles/` subdirectory.

```console
$ curl https://d3g5vo6xdbdb9a.cloudfront.net/tarball/opendistro-elasticsearch/opendistroforelasticsearch-1.4.0.tar.gz.sha512 -o opendistroforelasticsearch-1.4.0.tar.gz.sha512
$ shasum -a 512 -c opendistroforelasticsearch-1.4.0.tar.gz.sha512
shasum: ./tarfiles/opendistroforelasticsearch-1.4.0.tar.gz: No such file or directory
./tarfiles/opendistroforelasticsearch-1.4.0.tar.gz: FAILED open or read
shasum: WARNING: 1 listed file could not be read
$ cat opendistroforelasticsearch-1.4.0.tar.gz.sha512 
44579581e205459b51e720df0673df6c3dee396e3b1713a39f0ef6a70d2d6f7f7c85526a771b6367cb62db74c7399ffc7343ae04260674fc9ef4df6d084a919a  ./tarfiles/opendistroforelasticsearch-1.4.0.tar.gz
```

Perhaps the checksum file can be regenerated with a link to the tarball in the current directory?

**Comment by aetter** [comment]
Thanks a bunch, @IsaacHaze. I'm able to reproduce.

I went back and tested 1.2.0 and 1.3.0, and the checksum appears to have broken in between the two.

I've reported a bug in the build repository using your title and introductory text. I'm closing this out, but please keep an eye on https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/81. I've also added an ugly (temporary?) note to the docs: https://github.com/opendistro/for-elasticsearch-docs/commit/0325d257f4d329ceaa18593f4fc6f1461693c41c

Thanks again!
