### ISSUE TITLE
Unable to expose Kibana to  local network

### ISSUE THREAD

**Issue by kremlinkid** [opendistro/for-elasticsearch-docs#19]
there is no available parameter on the /etc/kibana/kibana.yml to configure Kibana to listen on any different address than localhost - i am currently running OpenDistro on a Centos VM set up on bridged mode on VirtualBox and i can't reach the server from any of my machines on my LAN - i can see other services exposed (Elasticsearch) but not Kibana.  

Any help is appreciated, thank you!

**Comment by aetter** [comment]
Hi @kremlinkid, even if they're not in the file/commented out, you can use all the standard Kibana parameters. In this case, I think setting `server.host` to your VM's IP should do the trick. Let me know. Thanks!
