### ISSUE TITLE
Not able to Browse Kibana/Elasticsearch

### ISSUE THREAD

**Issue by shrikant2109** [opendistro/for-elasticsearch-docs#191]
Hi,

I have followed the steps mentioned in the below link:
Elasticsearch - https://opendistro.github.io/for-elasticsearch-docs/docs/install/deb/
Kibana - https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/

I can see the elasticserch is working fine with below command:
curl -XGET https://localhost:9200 -u admin:admin --insecure

however when I try to access ElasticSearch/Kibana using the public IP address (with 9200/5601 port) the page is not available.

Thanks,
Shrikant

**Comment by ashwinkumar12345** [comment]
Can you try port forwarding: ssh <username>@<public_IP> -L 5601:localhost:5601?
