### ISSUE TITLE
example docker compose file incomplete

### ISSUE THREAD

**Issue by kapilt** [opendistro/for-elasticsearch-docs#2]
https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/

the end of the compose file(inline below), looks cut off , which makes it invalid yaml.

```
networks:
  odfe-net:
```

**Comment by aetter** [comment]
Hi @kapilt, thanks reporting. Have you run the Compose file? I know it looks a little weird, but in my testing, it works fine. I think the incomplete look of it is just the way the files are structured. You can see a similar example here: https://docs.docker.com/compose/compose-file/#endpoint_mode

**Comment by aetter** [comment]
Closing out. Feel free to reopen if there's an issue with the file!
