### ISSUE TITLE
Unable to install on Mac OSX

### ISSUE THREAD

**Issue by seanmbowen** [opendistro/for-elasticsearch-docs#213]
I am trying to following the instructions to install from a tar file. I have downloaded the tar file and extracted it and after running the ./opendistro-tar-install.sh script. I am getting an error that it can't find the bundled java. It is looking for it in a directory that does not exist:

could not find java in bundled jdk at /<local path>/opendistroforelasticsearch-1.6.0/jdk.app/Contents/Home/bin/java

I found the bundled java in the folder opendistroforelasticsearch-1.6.0/jdk/bin. If I try to execute the java executable manually then I get an error:

% ./java
zsh: exec format error: ./java

Is it that the installation is not compatible with the latest version of OSX?

**Comment by aetter** [comment]
Hey @seanmbowen, I've only tested in High Sierra, but as far as I know, the bundled JDK doesn't work. We note in the documentation, "If you have your own Java installation and you set JAVA_HOME in the terminal, macOS works as well."
