### ISSUE TITLE
how to connect es with elasticsearch-php-sdk

### ISSUE THREAD

**Issue by y80x86ol** [opendistro/for-elasticsearch-docs#22]
I install open distro for elasticsearch,and open ssl, like "https://127.0.0.1:9200", use default admin account.

but when i use elasticsearch-php-sdk to connect es,it tell me "SSL Problem Received fatal alert: unknown_ca". Am I wrong?

but I can access it by browser.

https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_security.html

thanks!

**Comment by aetter** [comment]
Hi @y80x86ol, did you add the `$myCert = 'path/to/cacert.pem';` line on that page for self-signed certificates? The default demo certificate that Open Distro for Elasticsearch uses is self-signed.

**Comment by y80x86ol** [comment]
> Hi @y80x86ol, did you add the `$myCert = 'path/to/cacert.pem';` line on that page for self-signed certificates? The default demo certificate that Open Distro for Elasticsearch uses is self-signed.

I add the cacert pem in my code, but still can't connection es.
ps: i used the Open Distro for Elasticsearch demo certificate

**Comment by aetter** [comment]
Hi @y80x86ol, I was able to get this working after some struggles. Can you try the following?

```php
<?php

require 'vendor/autoload.php';

use Elasticsearch\ClientBuilder;

$hosts = ['https://admin:admin@localhost:9200'];
$myCert = '/full/path/to/root-ca.pem';

$client = ClientBuilder::create()
                    ->setHosts($hosts)
                    ->setSSLVerification($myCert)
                    ->build();

$params = [
    'index' => 'test-index',
    'type' => '_doc',
    'id' => '1',
    'body' => ['testField' => 'abc']
];

$response = $client->index($params);
print_r($response);

?>
```

Then at the command line:

```bash
$ php -n -S 0.0.0.0:8000 index.php
```

And navigate to `0.0.0.0:8000` in your browser. Let me know. Thanks!

**Comment by y80x86ol** [comment]
@aetter thank you for your reply!
I tried you code ,but still echo 'No alive nodes found in your cluster'.

I disabling SSL verification,it works!

code like this:

`$hosts = ['https://admin:admin@127.0.0.1:9210'];

$client = ClientBuilder::create()
    ->setHosts($hosts)
    ->setSSLVerification(false)
    ->build();`

this is some same issues in other github:
https://github.com/elastic/elasticsearch-php/issues/854
https://github.com/elastic/elasticsearch-php/issues/850

**Comment by aetter** [comment]
Hi @y80x86ol, gotcha, I'm going to close this one out. Thanks!
