### ISSUE TITLE
Add 2 new Alerting settings and correct one existing

### ISSUE THREAD

**Issue by ftianli-amzn** [opendistro/for-elasticsearch-docs#223]
There are 2 new settings added in the Alerting plugin in this January (https://github.com/opendistro-for-elasticsearch/alerting/pull/143):

1. `opendistro.alerting.alert_history_enabled`
2. `opendistro.alerting.alert_history_retention_period`

And the current description of the setting `opendistro.alerting.alert_history_rollover_period` is not correct.

Reference:
The meanings for the settings from the pull request author:

- `opendistro.alerting.alert_history_enabled`: Enables or disables history indices being created

- `opendistro.alerting.alert_history_rollover_period`: How frequently we check to see if conditions are met to rollover history indices

- - `opendistro.alerting.alert_history_max_age`: A condition to rollover if the history index is at least this old

- - `opendistro.alerting.alert_history_max_docs`: A condition to rollover if the history index has at least this many docs

- `opendistro.alerting.alert_history_retention_period`: How long you want to keep histoy indices. History indices older than this will automatically be deleted. How often this is done is determined by the “alert_history_rollover_period” I believe

**Comment by aetter** [comment]
Hi @ftianli-amzn, thanks for the heads-up. Let me know how things look here: https://github.com/opendistro/for-elasticsearch-docs/commit/e1ba63767dc053c25676b4202abb698fdbef5691

We also gratefully accept PRs for situations like this in which you know exactly what needs tweaking. Thanks again!

**Comment by ftianli-amzn** [comment]
Thank you for the update! :clap: The update looks very accurate. Besides, I will share your idea with my team members.
