### ISSUE TITLE
opendistro_security_roles is a bit unclear

### ISSUE THREAD

**Issue by oscarkraemer** [opendistro/for-elasticsearch-docs#226]
Hi,
I'm setting up a multi tenant cluster and trying to figure out the mappings. It might be that I have misunderstood something fundamental, but this was a bit of a head-scratcher.

https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/api/#patch-user only mention how to map users to `backend_roles` but not to `opendistro_security_roles`. This meant that I spent way to long trying to map my normal user to `backend_role` instead of an `opendistro_security_roles` .  

In the end this closed issue solved the problem for me https://github.com/opendistro-for-elasticsearch/community/issues/155 . I guess `security roles` (not `opendistro security roles`)  is only mentioned once https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/users-roles/ .

I guess in my case I would not have had this issue if there where an API example of how to map to an `opendistro_security_roles` . 

Overall the user experience have been pretty nice.

**Comment by aetter** [comment]
Hi @oscarkraemer, thanks a bunch for reporting. When we first released the Security plugin, you could only add backend roles to users. I don't know when we added the ability to also directly map security roles, but in short, the docs haven't kept up with the times. When we get some free cycles, we'll reexamine our recommendations around how to work with users and roles, along with the API calls.

**Comment by keithhc2** [comment]
Hi @oscarkraemer, thanks for letting us know about this issue. We've updated the documentation to include how to map users to `opendistro_security_roles` when creating a user and updating a user's attributes, which you can find in the [Create User API section](https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/api/#create-user) and [Patch User section](https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/api/#patch-user).

Hope this helps!
