### ISSUE TITLE
Documentation for ODBC Driver

### ISSUE THREAD

**Issue by abbashus** [opendistro/for-elasticsearch-docs#229]
https://github.com/opendistro-for-elasticsearch/sql-odbc

- Installation for both Mac and Windows
- Connection to Tableau
- Connection to Excel.

**Comment by aetter** [comment]
Hey @abbashus, given how we currently "document" the [JDBC driver](https://opendistro.github.io/for-elasticsearch-docs/docs/sql/jdbc/) and the number of complaints we've received, it's highly likely that we'll do the same for the ODBC driver and just link to the repository.

**Comment by abbashus** [comment]
@aetter I am in processing of creating a PR on **sql-odbc** with documentation. I think we need to make a call whether to carry all the info from **sql-odbc** doc to  **for-elasticsearch-docs**.

If we go with keeping the whole documentation in **sql-odbc**, instead of providing the single link to the repo, we should provide **Table of Contents** linking to a separate doc.

@anirudha

**Comment by anirudha** [comment]
I prefer we keep all docs in one place, we can create a GH action for automation if required. But for a user/developer ( customer ) its a better experience to see all docs in one place. 

i'll also fix the JDBC docs and move them as a PR
