### ISSUE TITLE
Add examples directly on Kibana documentation rather than listing external links

### ISSUE THREAD

**Issue by ylwu-amzn** [opendistro/for-elasticsearch-docs#236]
For the Kibana documentation https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/

We can see some external link like "You can start Kibana using docker run after [creating a Docker network](https://docs.docker.com/engine/reference/commandline/network_create/) and starting Elasticsearch"
Why we ask user to jump to another page and learn how to create a Docker network? That definitely add more learning effort. How about we just put some simple workable examples directly on our ODFE documentation. So user can hand on quickly.

**Comment by aetter** [comment]
We don't recommend that method because it's such a pain and it's a Docker operation, not an ODFE one. The docker-compose file, which we do provide, is much simpler to use and maintain. https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/#sample-docker-compose-file
