### ISSUE TITLE
broken link on term level queries page

### ISSUE THREAD

**Issue by paul-brebner** [opendistro/for-elasticsearch-docs#241]
On Term level queries page this is a broken link:

http://www.staff.city.ac.uk/~sb317/papers/foundations_bm25_review.pdf

There's a downloadable pdf on this page which could replace it:

https://www.researchgate.net/publication/220613776_The_Probabilistic_Relevance_Framework_BM25_and_Beyond

**Comment by aetter** [comment]
Thanks a bunch @paul-brebner. I couldn't find anything outside of researchgate.net and academia.edu. Neither feels quite right as a link, so I went with the center of all human knowledge, Wikipedia, even though it doesn't go into the same level of detail. h-docs/commit/81de90c0ee96b67e5ddd6d31d50457793f32dc08

**Comment by paul-brebner** [comment]
Andrew, hi thanks, great Open source Elastticsearch documentation, works
well as intro to ES I think (I'm doing an intro blog on ES and will
certainly reference it).
Tricky googling ES documentation however as elastic.co gets the
hightest hits, and then it's not obvious if docs refer to Open source or
proprietary features!
And lots of ES documentation on the web is out of date!

Regards, Paul
