### ISSUE TITLE
OIDC in Config.yml not documented correctly

### ISSUE THREAD

**Issue by matty1979** [opendistro/for-elasticsearch-docs#242]
In config.yml documentation for OIDC documentation, the documents have for openid_auth_domain enabled: true instead of like I found in other issues, http_enabled:true and transport_enabled: true 

config.yml will not correctly update with the securityadmin.sh tool with these lines being incorrect.

**Comment by aetter** [comment]
Thanks @matty1979 https://github.com/opendistro/for-elasticsearch-docs/commit/92f0030c1833ebdc7294d3c6d9692a86cd926b02
