### ISSUE TITLE
Versioning ODFE documentation

### ISSUE THREAD

**Issue by sandeepkanabar** [opendistro/for-elasticsearch-docs#244]
Currently, there's no versioning mechanism in ODFE documentation and hence no way to refer documentation specific to older version e.g. say `0.10.0.0`. If someone wants to get started with an older version, then steps to install and get started quickly aren't there as well.

Can we introduce versioning in ODFE documentation at https://opendistro.github.io/for-elasticsearch-docs/.

Thoughts?

**Comment by aetter** [comment]
Hi @sandeepkanabar, thanks for the reminder. I've been meaning to add some older versions. 0.9.0 is here: https://opendistro.github.io/for-elasticsearch-docs/docs/other/#old-documentation-versions

This change bloats the build process a bit, so I might eventually host old versions elsewhere, but it should be OK for the time being.
