### ISSUE TITLE
API: create roles and rolesmapping

### ISSUE THREAD

**Issue by stempher** [opendistro/for-elasticsearch-docs#250]
Hi
If you create a role using api request:
```
PUT _opendistro/_security/api/roles/test-api
{
  "index_permissions": [{
    "index_patterns": [
      "test-*"
    ],
    "allowed_actions": [
      "read"
    ]
  },
  {
    "index_patterns": [
      "?kibana*"
    ],
    "allowed_actions": [
      "indices_all"
    ]
  }],
  "tenant_permissions": [{
    "tenant_patterns": [
      "global_tenant"
    ],
    "allowed_actions": [
      "kibana_all_write"
    ]
  }]
}
```
then it cannot be found in the web interface in the roles mapping section.
If you do role mapping via api, then an error is displayed in the web interface
![photo_2020-05-28_13-36-46](https://user-images.githubusercontent.com/23376762/83655526-35ecae80-a5c7-11ea-990a-07c3f94ceec9.jpg)
What am I doing wrong?

**Comment by stempher** [comment]
I used ODFE 1.3 and 1.6
But you have the role tab open. On the mapping tab you find the role created using the api request?

**Comment by aetter** [comment]
Correct, yeah. My calls:

```
PUT _opendistro/_security/api/roles/test-api
{
  "index_permissions": [{
    "index_patterns": [
      "test-*"
    ],
    "allowed_actions": [
      "read"
    ]
  },
  {
    "index_patterns": [
      "?kibana*"
    ],
    "allowed_actions": [
      "indices_all"
    ]
  }],
  "tenant_permissions": [{
    "tenant_patterns": [
      "global_tenant"
    ],
    "allowed_actions": [
      "kibana_all_write"
    ]
  }]
}

PUT _opendistro/_security/api/rolesmapping/test-api
{
  "users" : [ "admin" ]
}
```

I'm using our standard sample Docker Compose file on 1.8.0. I also tested with 1.3.0 and 1.6.0 and wasn't able to reproduce. What install type are you using?

<img width="861" alt="mapping" src="https://user-images.githubusercontent.com/9122297/83809826-f7f59600-a66b-11ea-92da-a27797dfbd81.png">

**Comment by stempher** [comment]
hmm, just try on your Docker Compose file (v. 1.8.0) - the error is reproducing...

**Comment by aetter** [comment]
Hey @stempher, how are you making these calls? curl? Postman? Some programming language? I'm using Postman, but if you're using curl or something, let me know the exact commands and I can try to reproduce again.

**Comment by stempher** [comment]
Hey @aetter,
I used terraform first, now I use curl on docker-compose:
```
curl -k -u admin:admin -H 'Content-Type: application/json' -H 'kbn-xsrf: true' -XPUT https://<ip>:9200/_opendistro/_security/api/roles/test-api -d '
{
  "index_permissions": [{
    "index_patterns": [
      "kibana_sample_data_logs"
    ],
    "allowed_actions": [
      "read"
    ]
  },
  {
    "index_patterns": [
      "?kibana*"
    ],
    "allowed_actions": [
      "indices_all"
    ]
  }],
  "tenant_permissions": [{
    "tenant_patterns": [
      "global_tenant"
    ],
    "allowed_actions": [
      "kibana_all_write"
    ]
  }]
}'

curl -k -u admin:admin -H 'Content-Type: application/json' -H 'kbn-xsrf: true' -XPUT https://<ip>:9200/_opendistro/_security/api/rolesmapping/test-api -d '
{
  "users": ["admin"]
}'
```

**Comment by aetter** [comment]
Hi @stempher, huh, that exact command works fine for me. I was hoping it was the `-H 'kbn-xsrf: true'` flag, which isn't necessary. What OS and curl version are you on? Can you try Postman or the following Python script?

```
import requests

endpoint = 'https://localhost:9200/' # add trailing slash
path = '_opendistro/_security/api/roles/my-new-role'
url = endpoint + path

payload = {
  "index_permissions": [{
    "index_patterns": [
      "kibana_sample_data_logs"
    ],
    "allowed_actions": [
      "read"
    ]
  },
  {
    "index_patterns": [
      "?kibana*"
    ],
    "allowed_actions": [
      "indices_all"
    ]
  }],
  "tenant_permissions": [{
    "tenant_patterns": [
      "global_tenant"
    ],
    "allowed_actions": [
      "kibana_all_write"
    ]
  }]
}

auth = ('admin', 'admin') # just for testing purposes
r = requests.put(url, auth=auth, json=payload, verify=False)
print(r.text)
```

**Comment by aetter** [comment]
Closing in favor of https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/230
