### ISSUE TITLE
Clarify the use of error_notification in policies

### ISSUE THREAD

**Issue by Bachib** [opendistro/for-elasticsearch-docs#251]
Hi, 

Please document the use of `error_notification` in [policies](https://opendistro.github.io/for-elasticsearch-docs/docs/ism/policies/#example-policy). What fields and contents can I place here. Also, an example for each type (Slack, Webhook, Chime) would help!

I am facing this error when I try to place anything else than `null` in the field : 

```
Sorry, there was an error
[parsing_exception] Failed to parse object: expecting token of type [START_OBJECT] but found [VALUE_STRING], with { line=1 & col=163 }
```

Thank you

**Comment by aetter** [comment]
My suspicion is that the object is no different than a regular [notification](https://opendistro.github.io/for-elasticsearch-docs/docs/ism/policies/#notification) and that we could just link to that section, but I've assigned to @ashwinkumar12345 for his thoughts.

**Comment by Bachib** [comment]
Indeed, the following worked :
```
"error_notification": {
            "destination": {
                "slack": {
                    "url": "https://hooks.slack.com/services/xxx/xxxxxx""
                }
            },
            "message_template": {
                "source": "the index is {{ctx.index}}",
                "lang": "mustache"
            }
        }
```


I was doing the following which is wrong : 

```
"error_notification": {
  "notification": {
    "destination": {
      "slack": {
        "url": "https://hooks.slack.com/services/xxx/xxxxxx"
      }
    },
    "message_template": {
      "source": "the index is {{ctx.index}}"
    }
  }
}
```

**Comment by ashwinkumar12345** [comment]
@Bachib and @aetter - Thanks for the feedback. I have added it to the docs - https://github.com/opendistro/for-elasticsearch-docs/pull/257.
