### ISSUE TITLE
Incorrect security role in documentation 

### ISSUE THREAD

**Issue by SagdeevRR** [opendistro/for-elasticsearch-docs#252]
In resource https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/security-roles/ it is writen the "set specify the .opendistro-alerting-alerts index", but in elastic have .opendistro-alerting-alert-history-2020.* indexes. May be need write .opendistro-alerting-alert* index.
Otherwise, an access error occurs and the user does not see the monitor created by him.

**Comment by aetter** [comment]
Hi @SagdeevRR, I think the docs are OK as-is. Ongoing alerts are indeed stored in the `.opendistro-alerting-alerts` index. Only after completion are they migrated to the history indices. To view your monitors, you actually need the `.opendistro-alerting-config` index.

I noticed that some of the UI steps aren't accurate, though, and made some tweaks. Thanks!
