### ISSUE TITLE
Add documentation on client certificate authentication

### ISSUE THREAD

**Issue by aetter** [opendistro/for-elasticsearch-docs#254]
Originally reported here: https://github.com/opendistro-for-elasticsearch/security/issues/188

Usage is very similar to https://docs.search-guard.com/latest/client-certificate-auth

It looks like Curator and Grafana support client certificate authentication. I *assume* you can make it work with most programming languages, as well. For example, the Python [Requests](https://2.python-requests.org/en/master/user/advanced/#client-side-certificates) library seems to support them.

In general, I think the right approach here is to include how to configure them on the ODFE side and a simple code sample to verify that they're working properly on the client side. The whole situation needs extensive testing.

**Comment by keithhc2** [comment]
Resolved as #426
