### ISSUE TITLE
Unable to see complete index names.

### ISSUE THREAD

**Issue by nipunsoni23** [opendistro/for-elasticsearch-docs#261]
Hello, I was using Index State Management plugin in Kibana and I was not able to see the full names of indices created. It created a lot of confusion as I was not able to expand the names.
<img width="1280" alt="Screenshot 2020-06-29 at 10 39 17 AM" src="https://user-images.githubusercontent.com/35968225/85975152-ed24eb80-b9f4-11ea-8da6-f4e1563c6d22.png">

**Comment by aetter** [comment]
Thanks a bunch, @nipunsoni23. I'm going to close this issue out, but I reported it over at the ISM project under https://github.com/opendistro-for-elasticsearch/index-management-kibana-plugin/issues/95.
