### ISSUE TITLE
install using helm page needs improvement

### ISSUE THREAD

**Issue by Hokwang** [opendistro/for-elasticsearch-docs#268]
Hi,

I am following Install and Configure > Helm page,
but there's some issue.

1. please write using helm version 3, so you can delete tiller section.

2. When using basic command `helm install opendistro-es opendistro-es-1.8.0.tgz` will deploy only 4 pod like below.
```
NAME                                               READY   STATUS    RESTARTS   AGE
odfe-stage-opendistro-es-client-749db79b79-5nrpb   1/1     Running   0          3m30s
odfe-stage-opendistro-es-data-0                    1/1     Running   0          3m30s
odfe-stage-opendistro-es-kibana-7bdc9f4f5-zjfjz    1/1     Running   0          3m31s
odfe-stage-opendistro-es-master-0                  1/1     Running   0          3m30s
```
but you mentioned using customvalues.yaml for `helm install --values=customevalues.yaml opendistro-es-1.8.0.tgz`
here's the thing is that beginner think it is difficult setting so wondering customvalues.yaml content.

3. let user knows how to set ingress (for example, nginx-ingress, local kubernetes cluster)
(simply `path: /odfe` does not work)

Thanks,

**Comment by ashwinkumar12345** [comment]
Thanks for the feedback. Added to the docs - https://github.com/opendistro/for-elasticsearch-docs/pull/287. For the questions on customvalues.yaml and setting an ingress, please open an issue here - https://github.com/opendistro-for-elasticsearch/opendistro-build/issues.
