### ISSUE TITLE
Time zone issues for {{ctx.periodStart}} and {{ctx.periodEnd}}

### ISSUE THREAD

**Issue by ourfor-pp** [opendistro/for-elasticsearch-docs#279]
What should I do to get the time right?

![image](https://user-images.githubusercontent.com/45449335/87522426-32fdd700-c6b8-11ea-956c-73f5326e9f23.png)

**Comment by aetter** [comment]
Hi @ourfor-pp, as best as I can tell, we only support UTC in these messages.
