### ISSUE TITLE
Does Template support ISM policy binding

### ISSUE THREAD

**Issue by xzy0223** [opendistro/for-elasticsearch-docs#284]
hi, dears

Does Template support ISM policy binding, I didn't see any description in docs

**Comment by aetter** [comment]
Hi @xzy0223, yes, pretty sure that's possible. We mention it in passing here: https://opendistro.github.io/for-elasticsearch-docs/docs/ism/#step-1-set-up-policies

> You can also include the policy_id in an index template so when an index is created that matches the index template pattern, the index will have the policy attached to it.

I think it's worth adding a sample index template that includes the `policy_id` to demonstrate how to have all new indices of a certain pattern inherit . Maybe here? https://opendistro.github.io/for-elasticsearch-docs/docs/ism/api/#add-policy-at-index-creation @ashwinkumar12345

**Comment by xzy0223** [comment]
> Hi @xzy0223, yes, pretty sure that's possible. We mention it in passing here: https://opendistro.github.io/for-elasticsearch-docs/docs/ism/#step-1-set-up-policies
> 
> > You can also include the policy_id in an index template so when an index is created that matches the index template pattern, the index will have the policy attached to it.
> 
> I think it's worth adding a sample index template that includes the `policy_id` to demonstrate how to have all new indices of a certain pattern inherit the policy. Maybe here? https://opendistro.github.io/for-elasticsearch-docs/docs/ism/api/#add-policy-at-index-creation @ashwinkumar12345

yes, I either don't know the correct syntax to bind the policy with template

maybe like this ?
`PUT _template/timeseries_template
{
  "index_patterns": ["timeseries-*"],                 
  "settings": {      
    "opendistro.index_state_management.policy_id": "ingest_policy"    
  }
}`

anybody can confirm?

**Comment by qreshi** [comment]
> maybe like this ?
> 
> ```
> PUT _template/timeseries_template
> {
>   "index_patterns": ["timeseries-*"],                 
>   "settings": {      
>     "opendistro.index_state_management.policy_id": "ingest_policy"    
>   }
> }
> ```
> 
> anybody can confirm?

Hi @xzy0223, yes I believe this is the correct way to apply a policy with a template.

Do note though that if you're using ISM 1.9 (Elasticsearch 7.8) it looks like they changed their templates a bit so the API in that case would be something like:

```
PUT _index_template/timeseries_template
```

**Comment by xzy0223** [comment]
thank you @qreshi , it's very helpful!
