### ISSUE TITLE
Sending the Json format log to Elasticsearch.

### ISSUE THREAD

**Issue by TPaulManohar** [opendistro/for-elasticsearch-docs#288]
Hi Team,
We are trying to send the JSON log to Opendistro Elastic search, which is in AWS environment. Can we use the file-beats module for sending the log to Elasticsearch.
Can you give us the Documentation for configuration.

**Comment by aetter** [comment]
Hi @TPaulManohar, there's no reason the open source version of Filebeat shouldn't be able to communicate with an ODFE cluster. The important thing is to make sure you're using the Apache 2 version, not the "default" version. The Apache 2 version is a bit buried, so look for "The pure Apache 2.0 licensed distribution, is available here." on the Filebeat downloads page.

See here for a configuration example. You'll of course have to tweaks hosts, certificates, credentials, etc.: https://opendistro.github.io/for-elasticsearch-docs/docs/troubleshoot/#beats
