### ISSUE TITLE
wrong api endpoint

### ISSUE THREAD

**Issue by holdfenytolvaj** [opendistro/for-elasticsearch-docs#293]
https://opendistro.github.io/for-elasticsearch-docs/docs/ism/

it says 
```
PUT _index_template/<template_name>
{
  "index_patterns": ["index_name-*"],                 
  "settings": {      
    "opendistro.index_state_management.policy_id": "policy_id"    
  }
}
```
should be called for create managed indeces according to the `index_pattern`, (but doesn't work)

but according to the ticket:
https://discuss.opendistrocommunity.dev/t/can-you-automatically-manage-indices/2034

it should be 
```
PUT _template/<template_name>
```
which indeed works.

**Comment by ashwinkumar12345** [comment]
@holdfenytolvaj - Only 1.9+ "_index_template" works and everything prior is "_template."
