### ISSUE TITLE
Monitoring setup for Opendistro elasticsearch cluster

### ISSUE THREAD

**Issue by eeshaisha** [opendistro/for-elasticsearch-docs#294]
Hi, 

We would like to monitor Opendistro Elasticsearch cluster health and Shards, all other metrics. Please help if we have any documentation. 

Always we are facing an issue with out of shards or reached shards count [1000/1000]

Thanks, 
Surendar

**Comment by ashwinkumar12345** [comment]
@eeshaisha - You can use the [CAT APIs](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/catapis/#shards). For more specific information, please ask on [the forum](https://discuss.opendistrocommunity.dev/).
