### ISSUE TITLE
Anamoly Detection for an exact host.ip or agent.name

### ISSUE THREAD

**Issue by ganeshcdac** [opendistro/for-elasticsearch-docs#297]
I can filter only value fields / boolean fields from indices. i am unable to choose the string filter from index. 

This is very much important for the case of anomaly detection for an host.
Is it possible to do the anomaly detection for the specific host.ip ?
Opendistro seems good to use and have more features related to siem  , kindly assist to get the above use case in filter.

I have  pasted the code used for my network infrastructure,
{
    "bool": {
        "filter": [
            {
                "range": {
                    "system.network.out.bytes ": {
                        "from": 500,
                        "to": null,
                        "include_lower": false,
                        "include_upper": true,
                        "boost": 1
                    }
                }
            },
            {
                "range": {
                    "system.process.cpu.total.value": {
                        "from": 600,
                        "to": null,
                        "include_lower": false,
                        "include_upper": true,
                        "boost": 1
                    }
                }
            },
            {
                "range": {
                    "system.process.cgroup.memory.mem.usage.bytes": {
                        "from": 500,
                        "to": null,
                        "include_lower": false,
                        "include_upper": true,
                        "boost": 1
                    }
                }
            },
            {
                "range": {
                    "system.process.cpu.total.pct": {
                        "from": 0.08,
                        "to": null,
                        "include_lower": false,
                        "include_upper": true,
                        "boost": 1
                    }
                }
            },
            {
                "term": {
                    "system.cpu.system.pct": {
                        "value": 9.81,
                        "boost": 1
                    }
                }
            }
        ],
        "adjust_pure_negative": true,
        "boost": 1
    }
}

For this usecase , I like to add string value of  specific hostname / agent.name.
By the way I will filter out the machine which is really affected, otherwise it is simply a measurement.

**Comment by ylwu-amzn** [comment]
Thanks for your interest in anomaly detection. Have replied you on ODFE forum.  https://discuss.opendistrocommunity.dev/t/anamoly-detection-for-the-exact-host-ip-or-agent-name/3549/2

Will close this issue.
