### ISSUE TITLE
deb (Debian/Ubuntu) support next to RPM

### ISSUE THREAD

**Issue by petericebear** [opendistro/for-elasticsearch-docs#3]
Do you have a deb package also in the pipeline/roadmap next to the RPM package?

**Comment by elfisher** [comment]
Hi @petericebear, we have an issue and backlog item open for this in our community page. Please use [the issue](https://github.com/opendistro-for-elasticsearch/community/issues/10) to 👍 the request. Closing this as a duplicate.
