### ISSUE TITLE
Unable to access Kibana installed Azure VM

### ISSUE THREAD

**Issue by gjfonte** [opendistro/for-elasticsearch-docs#30]
Hi, I have created a VM (CentOS 7.5) machine on Azure and followed the steps in the website. 
When I try to access Kibana using the public IP address (with 5601 port) the page is not available. I have also opened the inbound port 9200 and 5601 in the network firewall on the VM.
Any help?

**Comment by aetter** [comment]
Hi @gjfonte, there are bound to be a bunch of network considerations with Azure (I'm totally unfamiliar with network security in Azure), but have you set `server.host` in `kibana.yml` to the IP address/hostname of the server? From `kibana.yml`:

```yml
# Specifies the address to which the Kibana server will bind. IP addresses and host names are both valid values.
# The default is 'localhost', which usually means remote machines will not be able to connect.
# To allow connections from remote users, set this parameter to a non-loopback address.
#server.host: "localhost"
```

**Comment by gjfonte** [comment]
Thanks for your help. The problem was the IP address set in Kibana. The VM has 2 network adapters and I needed to change `kibana.yml` file to point to the correct IP address.
