### ISSUE TITLE
Autocomplete for search [kibana]

### ISSUE THREAD

**Issue by aradhell** [opendistro/for-elasticsearch-docs#31]
Hello,
Anyone else having issues about query Autocomplete? It is looking like not working at all.

(Package opendistroforelasticsearch-kibana-0.7.0-1.x86_64 already installed and latest version)

Thanks/

Syntax options
Our experimental autocomplete and simple syntax features can help you create your queries. Just start typing and you’ll see matches related to your data. See docs here.

**Comment by aetter** [comment]
Hi @aradhell, I'm able to reproduce and suspect that this is a bug on our end. I've reported to the engineering team and will try to keep you in the loop as they investigate.

**Comment by aetter** [comment]
Hi @aradhell, I did some more digging and got to the bottom of this issue. Essentially, autocomplete was included in OSS Kibana 6.3 and then removed in OSS Kibana 6.4.

You can test this if you fire up a 6.3 cluster, and if you compare the Kibana documentation for [6.3](https://www.elastic.co/guide/en/kibana/6.3/kuery-query.html) and [6.4](https://www.elastic.co/guide/en/kibana/6.4/kuery-query.html), you'll note the license change. :/
