### ISSUE TITLE
Add AnomalyDetection plugin installation URL

### ISSUE THREAD

**Issue by ylwu-amzn** [opendistro/for-elasticsearch-docs#314]
- This issue tracker is for problems with the Open Distro for Elasticsearch *documentation*: content requests

https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/plugins/, we only list three plugins' installation URLs on this doc. Community user is asking anomaly detection installation URL. Can you help add this URL: https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-anomaly-detection/opendistro-anomaly-detection-kibana-1.10.1.0.zip ?

**Comment by aetter** [comment]
:thumbsup: Thanks for the heads-up

https://github.com/opendistro/for-elasticsearch-docs/commit/da9629598ab579ec52e023d48e209fe213e02aba
