### ISSUE TITLE
Docker cluster example indicates "production workload"

### ISSUE THREAD

**Issue by mconner** [opendistro/for-elasticsearch-docs#325]
The section, [Start a Cluster](https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/#start-a-cluster) indicates a "production workload".  However, it describes use of a Docker Compose file, with two nodes for elastic search, and one for Kibana.  In a real production environment, wouldn't the cluster need to span machines?  As far as I understand it, docker-compose doesn't have a way to compose on multiple docker instances, which is where Docker Swarm comes in.  In which case, shouldn't this doc at least indicate that and, ideally, point to a docker swarm configuration?

**Comment by aetter** [comment]
Hi @mconner, yep, that's totally fair. I've updated the language to better reflect the intent: https://github.com/opendistro/for-elasticsearch-docs/commit/81a9cb359cc95b0636d78e1a8089aba542ad9c53

We've been hoping for a Docker Swarm PR a while now, but it seems like the majority of our users are on board with Helm and Kubernetes. If you come up with anything you're comfortable sharing, we'd love to check it out.
