### ISSUE TITLE
Securit API access control contradiction

### ISSUE THREAD

**Issue by chasebrewsky** [opendistro/for-elasticsearch-docs#328]
In the section on access control to the security API, there are two statements that seem to contradict themselves:

https://opendistro.github.io/for-elasticsearch-docs/old/0.9.0/docs/security/api/#access-control-for-the-api

It states that `opendistro_security.restapi.endpoints_disabled.<role>.<endpoint>: ["<method>", ...]` is used to PREVENT access to particular API's, but then later on it states:

> 
> For example, the following line grants the my-role role access to the PUT, POST, and DELETE methods of the ROLES URIs.
> 
> ```
> opendistro_security.restapi.endpoints_disabled.my-role.ROLES: ["PUT", "POST", "DELETE"]
> ```

Does the `endpoints_disabled` configuration prevent access or allow access?

Also, it's a bit unclear on whether the role configured in `opendistro_security.restapi.endpoints_disabled.<role>.<endpoint>: ["<method>", ...]` has to be placed in `opendistro_security.restapi.roles_enabled: ["<role>", ...]` too.

The general connotation I get from the names of the configuration sections is that roles must be given all access by placing them in `opendistro_security.restapi.roles_enabled` and that `opendistro_security.restapi.endpoints_disabled` removes some of that access, but if `opendistro_security.restapi.endpoints_disabled` actually ALLOWS access then it contradicts with the naming `endpoints_disabled`.

**Comment by aetter** [comment]
Thanks @chasebrewsky, yep, should have been "prevents" in that second case. I ran a few quick tests and tweaked the wording. https://github.com/opendistro/for-elasticsearch-docs/commit/c586dc87cc29985725d73921c59234437a2e0760
