### ISSUE TITLE
Performance Analyzer use too many /dev/shm

### ISSUE THREAD

**Issue by scf0920** [opendistro/for-elasticsearch-docs#33]
My opendistro cluster currently running on k8s. I found the /dev/shm was  used up, and i found Performance Analyzer is use /dev/shm.  But in k8s pod, /dev/shm only has 64MB. 
If I mount memory to /dev/shm, it may be "OOM". Can you give me some solution?

**Comment by ditac** [comment]
I have a couple of options in mind - 
* Create an inmemory volume and change the performance analyzer configuration file to point to the path - https://github.com/opendistro-for-elasticsearch/performance-analyzer/blob/master/pa_config/performance-analyzer.properties 
* You can also just mount the volume at /dev/shm and avoid changing the path.

**Comment by scf0920** [comment]
@aetter @ditac  Thanks too much. But I want to know is how to set this size, I worry about "OOM"

**Comment by aetter** [comment]
Hi @scf0920, sure, does the `--shm-size 1gb` flag not work for you?

**Comment by scf0920** [comment]
@aetter sorry, maybe I didn't express my meaning. What I mean is why is set to "1gb".  Is this calculated or by "experience dependence"? I feel this is related to the data size. Thanks.

**Comment by aetter** [comment]
Hi @scf0920, we've seen up to 1 GB of usage when testing heavy workloads, but I don't have details on what sort of data scale, indexing rate, and search rate "heavy" means. @ditac might know more.

**Comment by aetter** [comment]
Added a quick note and am closing out: https://github.com/opendistro/for-elasticsearch-docs/commit/f476ccb3cc1ef81d8bf5ea41aa2cbfa6d6d7345d
