### ISSUE TITLE
Configuration File contains reference to discovery.zen.minimum_master_nodes

### ISSUE THREAD

**Issue by mconner** [opendistro/for-elasticsearch-docs#330]
The example [config file](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/configuration/#configuration-file), (and actual config file in the docker image for 1.10.1 -- though its commented out) includes:
`discovery.zen.minimum_master_nodes: 1`

From what I can tell, this property is [no longer used ](https://www.elastic.co/blog/a-new-era-for-cluster-coordination-in-elasticsearch)with 7.x Elasticsearch (and, I therefore assume OpenDistro 1.x), and is not documented in the [Discovery and cluster formation settings](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/modules-discovery-settings.html).

**Comment by aetter** [comment]
Hi @mconner, sure, I don't think sample is doing a great deal of good, anyway. I've removed it. https://github.com/opendistro/for-elasticsearch-docs/commit/01e362dbdde7fc7fcadf90644dcbee25d0507d0f
