### ISSUE TITLE
unknown setting opendistro_security.disabled, documentation requires update?

### ISSUE THREAD

**Issue by abhijithshivaswamy** [opendistro/for-elasticsearch-docs#34]
Hi, i was setting up opendistro with security disabled, for development purpose, and folled the guide to disable security, in the docs here https://opendistro.github.io/for-elasticsearch-docs/docs/security/disable/ 

A exception is thrown indicating the setting  **opendistro_security.disabled**  is removed.

I removed all the settings related to opendistro_security including opendistro_security.disabled, and got it working without security.

I think, the setting has been removed, but the documentation is not updated.

**Comment by aetter** [comment]
Hi @abhijithshivaswamy, can you share your `elasticsearch.yml`, whether you're using the RPM installation or Docker install, and the timing of the error message?

If I fire up a fresh cluster using Docker, that line seems essential, but if you've already removed the plugin or the cluster is already running, I can imagine an error being thrown. Thanks!

**Comment by abhijithshivaswamy** [comment]
I Apologise for late reply.
I installed it using RPM, added the **opendistro_security.disabled**  in elasticsearch.yml, and moved the _**plugins/security**_ out of the installation folder of opendistro.

Then restarted opendistro, and above mentioned exception was being thrown in log file.

Here's the elasticsearch.yml (i have not changed any settings related to elasticsearch, only opendistro settings)

######## Start OpenDistro for Elasticsearch Security Demo Configuration ########
# WARNING: revise all the lines below before you go into production
opendistro_security.disabled: true
cluster.routing.allocation.disk.threshold_enabled: false
discovery.zen.minimum_master_nodes: 1
node.max_local_storage_nodes: 3
######## End OpenDistro for Elasticsearch Security Demo Configuration ########

**Comment by aetter** [comment]
Hi @abhijithshivaswamy, gotcha, that's what I suspected. I'll see if I can separate the two operations a bit in the documentation. Basically:

1. If you want to temporarily disable the plugin, but reenable it at a later time, you just add

**Comment by abhijithshivaswamy** [comment]
oh, i'm sorry then, i read it as both steps are required to disable security.

Thanks for clarifying @aetter  :+1:

**Comment by aetter** [comment]
Hi @abhijithshivaswamy, no worries at all. If you read it that way, others will, too. I'll separate it with headers or something. Thanks a bunch for reporting!
