### ISSUE TITLE
dls in document level permissions

### ISSUE THREAD

**Issue by fengxidi** [opendistro/for-elasticsearch-docs#340]
I have some doubts that elasticsearch query statements are DSL statements, why the keyword used by opendistro document-level permissions is dls

"dls": "{\"term\": { \"public\": true}}"

**Comment by aetter** [comment]
Hey @fengxidi, can you clarify your question here? The Elasticsearch DSL normally requires `{ "query": { ... } }`, but for DLS queries, you can omit that. As far as I know, they're otherwise identical.
