### ISSUE TITLE
No documentation for changing settings?

### ISSUE THREAD

**Issue by phillip-haydon** [opendistro/for-elasticsearch-docs#345]
https://opendistro.github.io/for-elasticsearch-docs/docs/ism/settings/

I want to set `opendistro.index_state_management.history.enabled` to false. But there's no information on how to do this. I assumed I just `put` it...

```
PUT /_cluster/settings
{
  "opendistro.index_state_management.history.enabled": false
}
```

But this results in:

```
{
  "Message": "Your request: '/_cluster/settings' payload is not allowed."
}
```

Doesn't appear to be assignable on a template either. So requesting documentation on how to change these settings.

**Comment by aetter** [comment]
Hi @phillip-haydon, it should work if you just wrap it in either `persistent` or `transient`, like other ES settings:

```
{
  "persistent" : {
    "opendistro.index_state_management.history.enabled": false
  }
}
```

https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/configuration/

**Comment by phillip-haydon** [comment]
Ahhh, yes, it worked with persistent.

The docs said: `and all can be marked persistent or transient.` and so I ignored this as I didn't think it was 'required'. 

Do all settings require it to be marked? I think the docs can be made a little clearer.

But thank you for helping me! Really appreciate it, spent many hours googling. :)
