### ISSUE TITLE
Custom scoring script is missing

### ISSUE THREAD

**Issue by kapilpendse** [opendistro/for-elasticsearch-docs#349]
The documentation [here](https://opendistro.github.io/for-elasticsearch-docs/docs/knn/#custom-scoring) mentions a `knn_store` script used in the example query as `source`. However, I could not find this script anywhere.

Also, on the same page, the documentation reads "Finally, use the `script_store` query to pre-filter your documents before identifying nearest neighbors", but the example query is `script_score`. This is probably a typo?

**Comment by aetter** [comment]
Hi @kapilpendse, thanks a bunch. I asked this same question to the team when I was testing the feature, but didn't actually put it into the content itself. I hope this helps: https://github.com/opendistro/for-elasticsearch-docs/commit/ed8eda98c8f662fc50d1b436c8ca338daf803572
