### ISSUE TITLE
Add documentation for cert generation

### ISSUE THREAD

**Issue by RMKD** [opendistro/for-elasticsearch-docs#36]
Current documentation has an instruction to "replace the demo certificates" [here](https://opendistro.github.io/for-elasticsearch-docs/docs/security/) but links to [a sample docker compose file](https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker-security/) that assumes the following files exist locally without describing how they are generated: 
- root-ca.pem
- esnode.pem
- esnode-key.pem
- kirk.pem
- kirk-key.pem

Incorrectly encoded pem files produce an only-slightly-helpful error message: `Your keystore or PEM does not contain a certificate. Maybe you confused keys and certificates.` which may be related to discrepancies between `PRIVATE KEY`, `PRIVATE ENCRYPTED KEY`, and `RSA PRIVATE KEY` headers which get pretty deep into openssl implementations. For instance, do the demo certs require PKCS#8?

It would help to have documentation and a simple script for securely generating the appropriate files, especially changing the admin client key from "kirk". It might also be useful to describe under what circumstances it is useful to generate non-admin client keys (such as [spock](https://docs.search-guard.com/latest/sgadmin) or kibana) 

Presumably the requirements originate from SearchGuard implementations, but configuring them is non-trivial and its not clear which method (or some other) is preferable: 
- [SearchGuard PKI scripts](https://docs.search-guard.com/latest/tls-certificates-sample-scripts)
- [SearchGuard sgtlstool](https://docs.search-guard.com/latest/offline-tls-tool.html)

**Comment by aetter** [comment]
Hi @RMKD, check out https://github.com/opendistro/for-elasticsearch-docs/pull/57 and let me know if yo uhave any feedback. I'll merge it myself eventually, but a second set of eyes is always helpful. Thanks!
