### ISSUE TITLE
KNN CosineSimilarity

### ISSUE THREAD

**Issue by doc113** [opendistro/for-elasticsearch-docs#377]
Hi! I can't understand the calculation formula of Cosine Similarity. I tried to calculate the values manually, but I get less than in API. Maybe you can write a formula? Thanks.

**Comment by aetter** [comment]
Hi @doc113 I believe @keithhc2 has addressed this here: https://github.com/opendistro/for-elasticsearch-docs/pull/388

Thanks a bunch for reporting!

https://opendistro.github.io/for-elasticsearch-docs/docs/knn/
