### ISSUE TITLE
Add description of -rev parameter securityadmin.sh

### ISSUE THREAD

**Issue by antonioazambuja** [opendistro/for-elasticsearch-docs#386]
https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/security-admin/

In this page, not contain description of **-rev** parameter. This parameter makes available resolution enviroment variables before apply Opendistro Security configurations.

Example of use case enviroment variable in config.yml:
- password: ${env.LDAP_PASSWORD}

Thanks!

**Comment by aetter** [comment]
Closing out in favor of https://github.com/opensearch-project/documentation-website/issues/17
