### ISSUE TITLE
Missing description for default Kibana Elasticsearch User

### ISSUE THREAD

**Issue by fwiedmann** [opendistro/for-elasticsearch-docs#39]
Hey,

I miss some Information about the default user which Kibana uses to connect to the Elasticsearch-Cluster. After hours of try-and-error I found this article: https://aws.amazon.com/de/blogs/opensource/change-passwords-open-distro-for-elasticsearch/

It describes that open-distro-for-elasticsearch requieres the user 'kibanaserver'.
Would be nice If you can add this information in your documents.

**Comment by aetter** [comment]
Hi @fwiedmann, thanks a bunch. We mention `kibanaserver` a few times in the documentation, but never really clarify what it does/why it's required. I've added a bit here: https://github.com/opendistro/for-elasticsearch-docs/commit/b2b088101b3f2af0a66409009477d252bd3ed035
