### ISSUE TITLE
Describe Objects attributes in Alerting available variables

### ISSUE THREAD

**Issue by JujuElk** [opendistro/for-elasticsearch-docs#390]
Hi all, 

I am using alerting module, and need to send some information through destination with mustache language. I am using this documentation to see what information I can send : 
[https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/monitors/#available-variables](url)

Unfortunately in your documentation, no description of objects : ctx.monitor.inputs, ctx.trigger.condition, ctx.trigger.actions. And in message preview module i see [object Object]

Can you please describe these objects to be able to see what we have inside ? 

Thanks, 
Julien Elkhiati

**Comment by keithhc2** [comment]
Hi @JujuElk, thanks for letting us know about the issue. We've expanded on the [variables table](https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/monitors/#available-variables), and it now includes more variables you can use in your Mustache templates to see more information about your monitors. 

Hope this helps!
