### ISSUE TITLE
Repository availability deb package

### ISSUE THREAD

**Issue by danilvoe** [opendistro/for-elasticsearch-docs#4]
Will there be an official deb repository with debian 8\9 packages?

**Comment by aetter** [comment]
Hi @danilvoe, thanks for opening an issue! A DEB package appears to be the most popular request so far. I'm going to close this issue as a duplicate, but I recommend checking out https://github.com/opendistro-for-elasticsearch/community/issues/10 and adding thumbs up as appropriate.
