### ISSUE TITLE
Acces Denied on plugin url

### ISSUE THREAD

**Issue by KoshalaBandara** [opendistro/for-elasticsearch-docs#400]
- This issue tracker is for problems with the Open Distro for Elasticsearch *documentation*: inaccuracies, content requests, etc.
- If you need help with troubleshooting, see [the community issue tracker](https://github.com/opendistro-for-elasticsearch/community) or [the forums](https://discuss.opendistrocommunity.dev/).
- Thanks so much for helping keep us organized. Please delete this text before posting your issue.

https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-alerting/opendistroAlertingKibana-1.9.0.0.zip

This is the url that is not working. Without this working I cannot install kibana plugin..

**Comment by aetter** [comment]
Thanks @KoshalaBandara, I suspect the team renamed a bunch of things out from under us when they went to camelCase for the new plugin names. Try https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-alerting/opendistro-alerting-1.9.0.0.zip

Commit: https://github.com/opendistro/for-elasticsearch-docs/commit/bc5040eb70ecb333dcc43036fa62d226a0bbb003
