### ISSUE TITLE
Issue with templates for system indices

### ISSUE THREAD

**Issue by Tonysykes** [opendistro/for-elasticsearch-docs#403]
We have recently upgraded to 1.12 and are having an issue with .opendistro-ism-managed-index-history indices including a few other system ones. We are unable to change the replicas. We were using the old template system which was working fine up until the upgrade (were on 1.8). As this broke we tried using the new template system however this does not work either. Here is the new template we created;

{
  "index_patterns": [
    ".opendistro-ism-managed-index-history-*"
  ],
  "template": {
    "settings": {
      "number_of_shards": 1,
      "number_of_replicas": 0,
      "index": {
        "opendistro.index_state_management.policy_id": "30days-delete"
      }
    }
  },
  "priority": 500,
  "version": 2,
  "_meta": {
    "description": "Fix the replica issue"
  }
}
This is happening on all our clusters. I was looking at Settings - Open Distro for Elasticsearch Documentation that says this is the correct method. I have used the index_template simulator and that shows the result we want, however this is not what is happening.

Thanks,

Tony.

**Comment by Tonysykes** [comment]
HI, Is there any movement on this as I am having to manually fix this on multiple clusters everyday.

**Comment by dbbaughe** [comment]
Hey @Tonysykes,

Just for confirmation - is the rest of the template working? As in does it apply the policy?

We recently changed in 1.12 the replicas/primary setting for the creation call for history indices for ISM to explicitly use 1 primary/1 replica. We were getting reports that it was creating too many replicas for people that still had the default 5 replica setting.

I'm guessing if everything else works except the template then it's just an issue of the call taking priority over your template. I'm not sure if it's possible to get a template to take precedence over the API call.. will have to look.

As a workaround for now you could update the 30days-delete to set the number of replicas to 0 also (or if you use it for more than that index create a 30days-delete-ism-history policy with it and have that one applied). If there isn't a way to make a template take precedence over the API call then I think the best we would be able to do is provide it as a ism setting for you to set in the cluster settings, although this will obviously not be ready until we make that change.

**Comment by dbbaughe** [comment]
Ah yeah, doesn't seem like the template will be able to override the API call we do internally.

https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-template.html#put-index-template-api-desc

**Comment by Tonysykes** [comment]
> 
> Just for confirmation - is the rest of the template working? As in does it apply the policy?
> 
Yes, it's applying the ISM policy.

**Comment by Tonysykes** [comment]
> 
> As a workaround for now you could update the 30days-delete to set the number of replicas to 0 also (or if you use it for more than that index create a 30days-delete-ism-history policy with it and have that one applied). If there isn't a way to make a template take precedence over the API call then I think the best we would be able to do is provide it as a ism setting for you to set in the cluster settings, although this will obviously not be ready until we make that change.

Will you be going forward with the ism setting so we can put the replica count into a policy? Will it be in the next release 1.13.x?

**Comment by dbbaughe** [comment]
Hey @Tonysykes,

Have added a PR here to make the ism history index shards/replicas configurable through the cluster settings.
https://github.com/opendistro-for-elasticsearch/index-management/pull/401

Will try to get it into the 1.13 release.
