### ISSUE TITLE
Trigger trigger multiple times

### ISSUE THREAD

**Issue by calipee** [opendistro/for-elasticsearch-docs#415]
In my usecase I'm grouping the monitor elasticsearch query results in buckets. 

For the trigger I'm iterating over the buckets and return true if the condition is met. 
Afterwards the trigger stops but I want it to continue and trigger **again** for each condition met. 
Is this possible? 

Thanks in advance.

**Comment by aetter** [comment]
Hey @calipee, evaluation scripts can only return true or false, and once they return, that's the end of the script. If I'm understanding your use case properly, though, I think you can achieve your desired outcome by adding multiple triggers to your monitors and using a piece of your evaluation logic in each trigger. Monitors can have lots of triggers, and if more than one meets its condition, you should get your multiple alerts. Let me know if that's helpful or if I'm misunderstanding something. 👍
