### ISSUE TITLE
Opendistro elasticsearch change default password without having docker-compose.yml

### ISSUE THREAD

**Issue by recepkabatas** [opendistro/for-elasticsearch-docs#43]
Hello , I'm trying to change default password of elasticsearch and kibana 
for instance admin:admin or kibanaserver:kibanaserver 

i took the image of container from https://hub.docker.com/r/amazon/opendistro-for-elasticsearch
and i didn't write any docker compose.yml file. i just run the container without .yml file

in 
/usr/share/elasticsearch/plugins/opendistro_security/securityconfig
internal_user.yml , i changed default password from here with new hash but i when i restart to container it's not changing i tried many times but still i get same default password 

i follow this page https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker-security/ 

can someone please help me to figure it out this issue?
Thanks a lot

**Comment by recepkabatas** [comment]
`./securityadmin.sh -cd ../securityconfig/ -icl -nhnv -cacert ../../../config/root-ca.pem  -cert ../../../config/kirk.pem  -key ../../../config/kirk-key.pem -p 172.18.0.5:9200
Open Distro Security Admin v6
ERR: An unexpected NumberFormatException occured: For input string: "172.18.0.5:9200"
Trace:
java.lang.NumberFormatException: For input string: "172.18.0.5:9200"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.amazon.opendistroforelasticsearch.security.tools.OpenDistroSecurityAdmin.main0(OpenDistroSecurityAdmin.java:274)
	at com.amazon.opendistroforelasticsearch.security.tools.OpenDistroSecurityAdmin.main(OpenDistroSecurityAdmin.java:133)
`

when i'm trying to change from securityadmin.sh (idk if it's correct way or not ) i tooked this error!

**Comment by aetter** [comment]
Hi @recepkabatas, I think you're close. After changing any of the files in the `securityconfig` directory, you need to run the `securityadmin.sh` script to load those changes into the `.opendistro_security` index.

To solve the error you're getting, I believe you can just remove `-p` from the comman. Everything else looks OK. See here for sample commands: https://opendistro.github.io/for-elasticsearch-docs/docs/security/security-admin/#basic-usage

**Comment by recepkabatas** [comment]
`Open Distro Security Admin v6
Will connect to localhost:9300 ... done
Elasticsearch Version: 6.5.4
Open Distro Security Version: 0.7.0.0
Connected as CN=kirk,OU=client,O=client,L=test,C=de
Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...
Clustername: docker-cluster
Clusterstate: YELLOW
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index already exists, so we do not need to create one.
Populate config from /usr/share/elasticsearch/plugins/opendistro_security/securityconfig
Will update 'security/config' with ../securityconfig/config.yml 
   SUCC: Configuration for 'config' created or updated
Will update 'security/roles' with ../securityconfig/roles.yml 
   SUCC: Configuration for 'roles' created or updated
Will update 'security/rolesmapping' with ../securityconfig/roles_mapping.yml 
   SUCC: Configuration for 'rolesmapping' created or updated
Will update 'security/internalusers' with ../securityconfig/internal_users.yml 
   SUCC: Configuration for 'internalusers' created or updated
Will update 'security/actiongroups' with ../securityconfig/action_groups.yml 
   SUCC: Configuration for 'actiongroups' created or updated
Done with success`
hello thank you for quick reply 
but this time i got this error i also think that i get close but still i cannot solve this problem :D

**Comment by aetter** [comment]
Hi @recepkabatas, I think you should be good to go. That looks like a success message to me. Can you log in to Kibana with the new password(s)?

**Comment by recepkabatas** [comment]
i have been looking for this error for 6 hours and i couldn't realize  it says that done with success :D :D 

Thank you so much for your help have a nice day
