### ISSUE TITLE
Format of parameter objects is fairly unclear

### ISSUE THREAD

**Issue by renodubois** [opendistro/for-elasticsearch-docs#432]
Hey all,

I'm new to Elasticsearch in general, so I've been trying to go over the docs quite a bit in order to figure things out. One particular pain point I've noticed is that some API definitions give very little information on what the requests bodies should look like. In particular, the one I just ran into is here: https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#indicescreate

While this gives me the name of the keys I need to send in my body, there's no explanation on what they should look like. I've tried looking around the docs for somewhere else that mentions this info but haven't found it (but even if it is there, a link or something to it would be appreciated, so that I can easily find out what's going on there).

The other case where I ran into this was on bulk data adding (https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#bulk) but I was able to find an example from the "Popular APIs" page (https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/popular-api/#index-several-documents-at-once) -- again, some sort of link to that to describe what the body should look like would be helpful. As someone new to the service, the description of "action-data pairs" isn't particularly helpful, since I don't know what the format should be.

Hopefully that makes sense and is useful feedback.

**Comment by aetter** [comment]
Agreed 100%. We're working (slowly) on a full REST API reference over here: https://github.com/opensearch-project/documentation-website/, so I'm going to close this out.
