### ISSUE TITLE
Add network and firewall requirements

### ISSUE THREAD

**Issue by nean-and-i** [opendistro/for-elasticsearch-docs#433]
please add network and firewall requirements to the documentation?

In case Opendistro is used in production on-premise, it would be great to get an overview of all the network requirements eg. firewall ports that needs to be opened.

Below a list of some ports (might not be complete) :

# Firewall Ports
port: comment
443: Kibana
5601: Kibana
9000: Cerebro
9200: REST
9250: cross cluster search
9300: nodes communication / transport
9600: required for Performance Analyzer

# ports according to elasticsearch network settings
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html

comment: ports
kibana: 443,5601
cerebro: 9000
http.port: 9200-9300
transport.profiles.default.port: 9300-9400
transport.profiles.client.port: 9500-9600
transport.profiles.dmz.port: 9700-9800

**Comment by aetter** [comment]
Closing in favor of https://github.com/opensearch-project/documentation-website/issues/18
