### ISSUE TITLE
Optimization required on ES service during ES High CPU usage  ( Data loss )

### ISSUE THREAD

**Issue by pcinnusamy** [opendistro/for-elasticsearch-docs#439]
Hi Team ,

On last week ,One of our  ODES (open distro Elastic search) cluster  experienced high CPU load (NewRelic) and caused the indices to be out of sync (temporarily outdated, but eventually recovered). 

We are suspecting  that ES itself is not optimized, and during high loads, this causes delay and missing data while syncing data from MongoDB.

Please can you suggest how to optimize the ODES during High CPU usage or How to optimize the Mongo connector Index

**Comment by aetter** [comment]
Hi there, it's true that high periods of sustained CPU load can cause Elasticsearch to throw errors, etc. Part of the solution is just throwing more hardware at the Elasticsearch cluster. The other part is having some sort of retry logic in your indexer (although in this case, it sounds like it recovered over time).
