### ISSUE TITLE
certs generation issue

### ISSUE THREAD

**Issue by wildc4t** [opendistro/for-elasticsearch-docs#443]
Hi guys!

I've followed manual for generating self signed certs https://opendistro.github.io/for-elasticsearch-docs/old/0.9.0/docs/security/generate-certificates/#generate-admin-certificate

Then in a month admin and node certs become expired. Some time was spent for error solving. 

Consider to add key -days ... in manual for generating certs step, plz. For all who will use the manual further

Thanks for the opendistro elasticsearch

**Comment by aetter** [comment]
Hi @wildc4t, thanks a bunch for the suggestion -- totally fair, and an oversight on my part. I only mention `-days` in the root cert, but of course it applies to the others, as well. I've tried to clarify things here: https://github.com/opendistro/for-elasticsearch-docs/commit/6e54a28132add3f224e22f33d14392e011246678

Thanks again!
