### ISSUE TITLE
Documentation - policy attributes does not include the "ism_template" field

### ISSUE THREAD

**Issue by yanivpl5** [opendistro/for-elasticsearch-docs#446]
Please update the documentation.
https://opendistro.github.io/for-elasticsearch-docs/docs/im/ism/policies/
Please add the "ism_template" field to the policy object.

Thanks

**Comment by ashwinkumar12345** [comment]
Thanks for the feedback. Added -https://opendistro.github.io/for-elasticsearch-docs/docs/im/ism/policies/.
