### ISSUE TITLE
Patching a role with "add" operation is replacing the tenant patterns

### ISSUE THREAD

**Issue by JohnMops** [opendistro/for-elasticsearch-docs#450]
Hi everyone, 

I am trying to implement an API call to add tenant patterns to a specific role that is mapped to multiple users and then remove it once the troubleshooting is done. 

When sending a request to https://localhost:9200/_opendistro/_security/api/roles/somerole?pretty with the body of: 

    `[
      {
        "op": "add", "path": "/tenant_permissions/0/tenant_patterns", "value": ["test"]
      }
    ]`

The tenant patterns are changing from: 

    ` "tenant_permissions" : [
          {
            "tenant_patterns" : [
              "global_tenant"
            ],
            "allowed_actions" : [
              "kibana_all_write"
            ]
          }
        ],`

To this : 

    ` "tenant_permissions" : [
          {
            "tenant_patterns" : [
              "test"
            ],
            "allowed_actions" : [
              "kibana_all_write"
            ]
          }
        ],`

Expected: I would expect the call to add the new pattern to the list instead of acting the same way as the "replace" operation. 
Appreciate any help.

**Comment by JohnMops** [comment]
IS there anyone that can help ?

**Comment by aetter** [comment]
Hi @JohnMops, thanks for reporting. This looks like a bug to me. I've reported it over at the security repository as https://github.com/opendistro-for-elasticsearch/security/issues/1099.

**Comment by JohnMops** [comment]
Any news on this one? @aetter

**Comment by aetter** [comment]
Hi @JohnMops, nothing to report. I'm reopening this issue so that we can fix the link (which now 404s) whenever the security team finishes their housekeeping, though.

**Comment by JohnMops** [comment]
> Hi @JohnMops, nothing to report. I'm reopening this issue so that we can fix the link (which now 404s) whenever the security team finishes their housekeeping, though.

Thank you very much

**Comment by aetter** [comment]
Hi @JohnMops, I'm going to close this out again in favor of https://github.com/opensearch-project/security/issues/1099
