### ISSUE TITLE
Add timezone information to alerting documentation

### ISSUE THREAD

**Issue by ianadeem** [opendistro/for-elasticsearch-docs#452]
In the documentation for the alerting feature, I could not find any information about what timezone is used for the cron expressions. It is probably either UTC or the system timezone. Could this information please be added to the docs.

**Comment by keithhc2** [comment]
Hi @ianadeem, thanks for reporting the issue! You can actually choose the timezone you want to use with your cron expressions. If you're using Kibana, you can use the "Select a timezone" dropdown menu to select what timezone to associate your cron expression with. If you're using the API, you can [specify a timezone in your cron expression](https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/api/#request-1). 

Hope this helps!
