### ISSUE TITLE
Unable to install standalone Kibana odfe plugin for kibana version 7.10.0

### ISSUE THREAD

**Issue by Madhanbaskar** [opendistro/for-elasticsearch-docs#455]
I'm using elasticsearch & kibana instance v7.10.0. I want to install odfe plugin on elasticsearch & kibana,
As per the odfe prerequisite documentation, I have to install opendistroReportsKibana(v1.12.0.0).
When I use this command to install v1.12.0.0 odfe plugin ---- **sudo bin/kibana-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-reports/linux/x64/opendistroReportsKibana-1.12.0.0-linux-x64.zip** the plugin is not getting installed.

I need the url of reports kibana plugin url for v1.12.0.0. Kindly help!

**Comment by aetter** [comment]
Hi @Madhanbaskar, sure, we keep changing the naming scheme for the plugins. We should really rename/link to every old version using the new naming scheme, but for now, It's https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-reports/linux/x64/opendistroReportsKibana-1.12.0.0.zip
