### ISSUE TITLE
Is it possible to execute an approximate nearest neighbour search by using the document id as a parameter? 

### ISSUE THREAD

**Issue by olsi-qose** [opendistro/for-elasticsearch-docs#467]
In the docs it is specified that the `knn` query can be used to search nearest neighbours.
```
GET my-knn-index-1/_search
{
  "size": 2,
  "query": {
    "knn": {
      "my_vector2": {
        "vector": [2, 3, 5, 6],
        "k": 2
      }
    }
  }
}
```

The dimensionality of the data is approximately 1300 embeddings. I was wondering if it is possible to query knn results by passing the id of the ES document instead of the whole vector?

**Comment by aetter** [comment]
Hi @olsi-qose not as far as I know -- I believe you have to get the document you want first and then pass over the appropriate field as your query -- but I've tagged a couple people who are more knowledgeable than me. @jmazanec15 @vamshin.

**Comment by olsi-qose** [comment]
Thank you @aetter!

**Comment by aetter** [comment]
Closing this out in favor of https://github.com/opendistro-for-elasticsearch/k-NN/issues/341.
