### ISSUE TITLE
GET _opendistro/_alerting/monitors/alerts api returning http error code 404 

### ISSUE THREAD

**Issue by rini2208** [opendistro/for-elasticsearch-docs#479]
While trying to fetch monitors for alert using api GET _opendistro/_alerting/monitors/alerts, i am getting error 404.

**Comment by aetter** [comment]
Hi @rini2208, which version of ODFE are you running? Get alerts is a relatively recent addition, so if you're running an older version, you might not have it.

**Comment by rini2208** [comment]
Hi Andrew, I am trying api via curl command, other apis are working fine
without ODFE.

**Comment by rini2208** [comment]
Hi, with ODFE version 1.1.0 which is latest, i am getting below error for
api.

odfe-cli  curl get --path "_opendistro/_alerting/monitors/alerts"

get Command failed.
Reason: GET https://localhost:9200/_opendistro/_alerting/monitors/alerts
giving up after 5 attempt(s): Get "
https://localhost:9200/_opendistro/_alerting/monitors/alerts": http: server
gave HTTP response to HTTPS client

**Comment by rini2208** [comment]
Hi,
Find details below . _opendistro/alerting/stats returning output but
_opendisrto/alerting/monitors/alerts returns nothing.

[image: image.png]

**Comment by rini2208** [comment]
![image](https://user-images.githubusercontent.com/83286730/116286386-ccf8c100-a7ac-11eb-99a8-455411d7dfce.png)

**Comment by aetter** [comment]
So there's odfe-cli and ODFE itself. You might have started ODFE from the tarball or Docker or wherever. That's the version number we need. You can figure it out if you run _cat/plugins, or you might have it in your Docker command, etc.

**Comment by rini2208** [comment]
Version number 1.1.0 and i am running it from inside kuberentes container of kuberenetes.

**Comment by aetter** [comment]
Hey @rini2208, that API is indeed not present in that version. Try upgrading to at least 1.11 (though ideally 1.13.2). odfe-cli is versioned independently, so CLI 1.1 is fine to use with ODFE 1.13.2.
