### ISSUE TITLE
Update Alert definition for the Alerting plugin

### ISSUE THREAD

**Issue by qreshi** [opendistro/for-elasticsearch-docs#481]
This is referring to the `Key Terms` section here:
https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/monitors/

In Alerting, the 'Alert' is the object that represents an event for a particular Trigger. When an Alert is created, subsequent Actions associated with the Trigger are executed **one of which** can be a notification. The current definition implies that the Alert **is** the notification which is not correct and can cause confusion around the framework's behavior.

The request is to revisit the `Key Terms` (mainly `Alert`) and ensure the distinction between the components is clear.

**Comment by keithhc2** [comment]
Closed with #483
