### ISSUE TITLE
403 - Acess denied error while installing elasticsearch alerting plugin

### ISSUE THREAD

**Issue by srksumanth** [opendistro/for-elasticsearch-docs#486]
I am trying to install plugins from the plugins page :  https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/plugins/

To install the alerting plugin, I ran the following command for elasticsearch v7.4.2
`sudo bin/elasticsearch-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-alerting/opendistro-alerting-1.4.0.0.zip`
 
It fails with error code 403 - Access Denied.
Seems like the file [https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-alerting/opendistro-alerting-1.4.0.0.zip](https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-alerting/opendistro-alerting-1.4.0.0.zip) is not public.

This issue seems to exist for other plugins as well.
Thanks.

**Comment by aetter** [comment]
Hi @srksumanth, apologies about this. The team changed the naming scheme of the plugins at least twice and didn't go back and rename/forward to the older artifacts. Try https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-alerting/opendistro_alerting-1.4.0.0.zip
