### ISSUE TITLE
Contradictory statement in documentation

### ISSUE THREAD

**Issue by geek981108** [opendistro/for-elasticsearch-docs#489]
There's a confusing  statement in the documentation of Open distro for ElasticSearch located at `https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/api/#update-configuration`

The original text is as follows：

`Creates or updates the existing configuration using the REST API rather than securityadmin.sh. This operation can easily break your existing configuration, so we recommend using securityadmin.sh instead. See Access control for the API for how to enable this operation.`

In the first half of the paragraph the doc recommand us to use REST API and use securityadmin.sh in the rest of it.

Overall view of the full text, Using REST API should be recommanded.

**Comment by aetter** [comment]
Hi @geek981108, agreed that the wording is a bit confusing. For most things -- creating users, roles, etc. -- the REST API is the better way to go. For updating the configuration, though, the REST API is pretty risky. We even keep the request disabled by default. `securityadmin.sh` is much safer. I've tried to clarify a bit here: https://github.com/opendistro/for-elasticsearch-docs/commit/e24c6a7557cb3636d66bcb2bcc125b5d3bfcddfe

**Comment by geek981108** [comment]
Thank you for your work！
