### ISSUE TITLE
Add documentation for Kubernetes deployment

### ISSUE THREAD

**Issue by vniche** [opendistro/for-elasticsearch-docs#49]
Current documentation has an demo on [getting things running with docker](https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/) but to get things ready in Kubernetes it's a bit painful with just that, and it being a well-known broadly used platform i think it is an worthy effort.

I have a multi-host (cluster) installation successfully running in an private cluster, let me know if you guys have some interest for me to share it/create a PR with the manifests (yamls) i used.

**Comment by aetter** [comment]
Hi @vniche, absolutely we have interest. If you want to take a crack at it, I'd recommend a new file, something like `docs/install/kubernetes.md` to cover the basic steps, gotchas, etc., linking back to the Docker content as necessary. Thanks!

**Comment by vniche** [comment]
@aetter give me heads up if any on the current version of #59 , i'll give it some more attention on the next days.

**Comment by oddlittlebird** [comment]
Hi there, technical writer here. I am new to open source, but interested in helping with documentation.
