### ISSUE TITLE
How to Enable HTTP.CORS (Cross-Origin Resource Sharing)

### ISSUE THREAD

**Issue by SLiNv** [opendistro/for-elasticsearch-docs#55]
I tried to put this in docker-compose.yml but didn't work.
```yml
environment:
      - cluster.name=odfe-cluster
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM

      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - opendistro_security.ssl.http.enabled=false
```

Does Open Distro supports CORS with different config keys like ```opendistro_security.xxx``` or it is currently impossible?

**Comment by aetter** [comment]
Hi @SLiNv, as far as I know, CORS configuration shouldn't be any different from Elasticsearch without the plugins. I'll leave this issue open in case anyone else has tips.

**Comment by SLiNv** [comment]
@aetter Thank you for the response. I was able to enable CORS. Last time was due to volume not dropped so the first config file was not updated when I re-initiated the container. This can be closed.
