### ISSUE TITLE
Kibana status is  Yellow - "plugin:opendistro_security@6.5.4 Tenant indices migration failed"

### ISSUE THREAD

**Issue by brycelin** [opendistro/for-elasticsearch-docs#6]
Using the sample docker-compose.yml (https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/).

then run:
docker-compose up
Able to login to Kibana and everything works fine.

then:
docker-compose stop
docker-compose start

Able to login to Kibana but see error:
Kibana status is  Yellow
plugin:opendistro_security@6.5.4    Tenant indices migration failed

Unable to do anything in Kibana. Any help would be appreciated.

**Comment by aetter** [comment]
Hi @brycelin, thanks a bunch for reporting. I'm able to reproduce your issue and have asked a couple engineers to look into it. In the meantime (and believe me, I know it stinks), you can use `docker-compose down -v` to purge all data when you bring down the cluster. I'll update here when I've got some word. If there are mitigation steps, I'll document them, and if it's a straight-up plugin bug, I'll create a new issue in the Security plugin repository.

**Comment by aetter** [comment]
Hi @brycelin, thanks again. This is a bug in the Security plugin. Opening an issue there and closing this one out.

https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/1
