### ISSUE TITLE
Alert id is not available

### ISSUE THREAD

**Issue by ancazzz** [opendistro/for-elasticsearch-docs#60]
The documentation mentions that the ctx variable has a field 'alert' with the following content:
"The current, active alert (if it exists). Includes ctx.alert.id, ctx.alert.version, and ctx.alert.isAcknowledged. Null if no alert is active."

However, when verifying the ctx.alert field in my triggered action message, I get the following result:
{state=ACTIVE, error_message=null, acknowledged_time=null, last_notification_time=1555580484091}

The properties are different and there is no alert id or version. The alert id is indispensable for acknoledging the alert using the API.

**Comment by aetter** [comment]
Hi @ancazzz, this is resolved in code and should be fixed in version 0.9.0: https://github.com/opendistro-for-elasticsearch/alerting/pull/26
