### ISSUE TITLE
facing issues while configuring kibana with existing stock elastic search

### ISSUE THREAD

**Issue by viveklanjekar** [opendistro/for-elasticsearch-docs#63]
we have a existing elastic search cluster ( stock docker.elastic.co/elasticsearch/elasticsearch:6.6.2)

i tried using opendistro kibana with it. as my usecase is to hava alerting on Elastic search data.

few issues i faced while doing it

1> as my existing Elastic search is running on http and doest have security plugin, i disabled security plugin in open distro plugin to get kibana started
2> now i can see data in kibana but alerting dint work. bellow is error in kibana logs

Alerting - ElasticsearchService - search { [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id=".opendistro-alerting-config" & index_uuid="_na_" & index=".opendistro-alerting-config" } :: {"path":"/.opendistro-alerting-config/_search","query":{},"body":"{\"query\":{\"term\":{\"monitor.name.keyword\":\"test\"}}}","statusCode":404,"response":"{\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\".opendistro-alerting-config\",\"index_uuid\":\"_na_\",\"index\":\".opendistro-alerting-config\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\".opendistro-alerting-config\",\"index_uuid\":\"_na_\",\"index\":\".opendistro-alerting-config\"},\"status\":404}"}
    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4935:19)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 404,
  displayName: 'NotFound',
  message:
   '[index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id=".opendistro-alerting-config" & index_uuid="_na_" & index=".opendistro-alerting-config" }',
  path: '/.opendistro-alerting-config/_search',
  query: {},
  body:
   { error:
      { root_cause: [Array],
        type: 'index_not_found_exception',
        reason: 'no such index',
        'resource.type': 'index_or_alias',
        'resource.id': '.opendistro-alerting-config',
        index_uuid: '_na_',
        index: '.opendistro-alerting-config' },
     status: 404 },
  statusCode: 404,
  response:
   '{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":".opendistro-alerting-config","index_uuid":"_na_","index":".opendistro-alerting-config"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":".opendistro-alerting-config","index_uuid":"_na_","index":".opendistro-alerting-config"},"status":404}',
  toString: [Function],
  toJSON: [Function] }
Alerting - ElasticsearchService - search { [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id=".opendistro-alerting-config" & index_uuid="_na_" & index=".opendistro-alerting-config" } :: {"path":"/.opendistro-alerting-config/_search","query":{},"body":"{\"query\":{\"term\":{\"monitor.name.keyword\":\"test\"}}}","statusCode":404,"response":"{\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\".opendistro-alerting-config\",\"index_uuid\":\"_na_\",\"index\":\".opendistro-alerting-config\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\".opendistro-alerting-config\",\"index_uuid\":\"_na_\",\"index\":\".opendistro-alerting-config\"},\"status\":404}"}
    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4935:19)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 404,
  displayName: 'NotFound',
  message:
   '[index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id=".opendistro-alerting-config" & index_uuid="_na_" & index=".opendistro-alerting-config" }',
  path: '/.opendistro-alerting-config/_search',
  query: {},
  body:
   { error:
      { root_cause: [Array],
        type: 'index_not_found_exception',
        reason: 'no such index',
        'resource.type': 'index_or_alias',
        'resource.id': '.opendistro-alerting-config',
        index_uuid: '_na_',
        index: '.opendistro-alerting-config' },
     status: 404 },
  statusCode: 404,
  response:
   '{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":".opendistro-alerting-config","index_uuid":"_na_","index":".opendistro-alerting-config"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":".opendistro-alerting-config","index_uuid":"_na_","index":".opendistro-alerting-config"},"status":404}',
  toString: [Function],
  toJSON: [Function] }
{"type":"response","@timestamp":"2019-04-21T18:16:33Z","tags":[],"pid":1,"method":"post","statusCode":200,"req":{"url":"/api/alerting/_search","method":"post","headers":{"host":"internal-newkibana01-corp-grabpay-com-1568899982.ap-southeast-1.elb.amazonaws.com","accept":"application/json, text/plain, */*","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.5","content-type":"application/json;charset=utf-8","kbn-version":"6.6.2","referer":"http://internal-newkibana01-corp-grabpay-com-1568899982.ap-southeast-1.elb.amazonaws.com/app/opendistro-alerting","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:66.0) Gecko/20100101 Firefox/66.0","x-forwarded-for":"10.77.0.195","x-forwarded-port":"80","x-forwarded-proto":"http","content-length":"98","connection":"keep-alive"},"remoteAddress":"10.77.5.236","userAgent":"10.77.5.236","referer":"http://internal-newkibana01-corp-grabpay-com-1568899982.ap-southeast-1.elb.amazonaws.com/app/opendistro-alerting"},"res":{"statusCode":200,"responseTime":4,"contentLength":9},"message":"POST /api/alerting/_search 200 4ms - 9.0B"}

let me know if any more info needed

**Comment by viveklanjekar** [comment]
is this because alerting plugin not installed on elastic search cluster?

**Comment by aetter** [comment]
Hi @viveklanjekar, yep, you have to have the Alerting plugin installed on each Elasticsearch node. Otherwise, the Kibana Alerting plugin doesn't have the necessary backend APIs, and all requests to the cluster fail. Check out https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/
