### ISSUE TITLE
On page "Standalone plugin install" no links to Standalone Kibana Plugins

### ISSUE THREAD

**Issue by olekkry** [opendistro/for-elasticsearch-docs#64]
Hi. I tried to install opendistro_alerting plugin from page "[Standalone plugin install](https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/)" and can't find any proper links to Standalone Kibana Plugins.
I guess, someone forgot to publish this links.
Can someone tell me links to archives with plugins?

**Comment by olekkry** [comment]
found urls to packages of Kibana Plugins in docker history amazon/opendistro-for-elasticsearch-kibana output

https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-security/opendistro_security_kibana_plugin-0.8.0.0.zip
https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-alerting/opendistro-alerting-0.8.0.0.zip

**Comment by allenyin96** [comment]
Hi, kibana standalone plugin download are now updated on our website [here](https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/plugins/)

Closing.

**Comment by sehdorn** [comment]
Hi.
Would it be possible to publish the binaries in a more "official" place, e.g. the maven-repo, like here:
https://repo1.maven.org/maven2/com/amazon/opendistroforelasticsearch/
that would be really awesome

thx
