### ISSUE TITLE
Cannot setup triggers for Monitor

### ISSUE THREAD

**Issue by rajansapra007** [opendistro/for-elasticsearch-docs#66]
I’ve created a monitor based on Extraction Query. I am trying to create trigger for that, when I press the create button, it doesn’t do anything. I mean it neither creates that trigger nor shows any error message. How to resolve this issue?
Please help!!

**Comment by alolita** [comment]
Hi @rajansapra007 can you provide more details about your monitor and trigger setup. Please use the community forums at https://discuss.opendistrocommunity.dev/ for questions so that the larger community can share their know-how too.
