### ISSUE TITLE
Logstash cannot connect to Elastic

### ISSUE THREAD

**Issue by jirisafar** [opendistro/for-elasticsearch-docs#72]
Hi,

we are facing problem with our new installed LOGSTASH and new installed Elastic with OpenDistro.

We want to send log to the Elastic via LOGSTASH but logstash cannot connect Elastic.

We have simple installation of Logstash with this output file:
output {
  elasticsearch {
    hosts => "https://ourserver:9200"
    index => "logstash-%{+YYYY.MM.dd}"
    user => "admin"
    password => "admin"
    document_type => "log"
  }
}

But this is what we get when Logstash try to connect: 

ogstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"https://admin:xxxxxx@ourserver:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [https://admin:xxxxxx@ourserver:9200/][Manticore::ClientProtocolException] PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"}

Any idea what is wrong? If I try to go via browser https://ourserver:9200 then it ask for login and I type admin admin it works.

**Comment by aetter** [comment]
Hi @jirisafar, a few potential problems here:

* I think you just want `ourserver:9200` rather than adding https.
* Try adding `ssl => true`.
* Either add `ssl_certificate_verification => false` or `cacert => "/path/to/root-ca.pem"`.

**Comment by jirisafar** [comment]
Hi,

I have used our *.pem SSL and it seems that it is working. I will test it and post output here:
BTW this is how the config looks like now:

output {
  elasticsearch {
    hosts => "https://ourserver:9200/"
    index => "logstash-%{+YYYY.MM.dd}"
    document_type => "log"
    user => "admin"
    password => "admin"
    ssl => true
    cacert => "/pem/logstash.pem"
  }
}

**Comment by jirisafar** [comment]
That solved the problem and everything is working well.
