### ISSUE TITLE
Export Alert configuraiton

### ISSUE THREAD

**Issue by gani247** [opendistro/for-elasticsearch-docs#75]
is there any way to **EXPORT/IMPORT** Alert configurations.

**Comment by aetter** [comment]
Hi @gani247, yep, your alerting configuration is just another index in Elasticsearch, so you can take and restore snapshots of it just like any other index. The one you're looking for is `.opendistro-alerting-config`. I added a sentence of clarification here: https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/settings/

**Comment by fabiohecht** [comment]
What would be really useful is if the Saved Objects API would work with alerts as well.
