### ISSUE TITLE
404 error https://opendistro.github.io/for-elasticsearch-docs/docs/install/override-security

### ISSUE THREAD

**Issue by rajserc** [opendistro/for-elasticsearch-docs#76]
In page
https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/

 pass your own certificates link fails with page not found.

404 https://opendistro.github.io/for-elasticsearch-docs/docs/install/override-security

**Comment by aetter** [comment]
@rajserc thanks a bunch for reporting. Fixed here: https://github.com/opendistro/for-elasticsearch-docs/commit/2d04c60506a29b34d0e1afa423a0e15738a0998a
