### ISSUE TITLE
Kerberos docs improvements

### ISSUE THREAD

**Issue by dpotapov** [opendistro/for-elasticsearch-docs#77]
https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/#kerberos

1. It is not clear on Kerberos configuration page that `acceptor_principal` should be prefixed with `opendistro_security.kerberos` like other options do.
2. I guess that statement `Due to security restrictions, the keytab file must be placed in the <open-distro-install-dir>/conf or a subdirectory` should refer `/config` directory (not `/conf`).

**Comment by aetter** [comment]
Hi @dpotapov, thanks a bunch for reporting. Let me know if https://github.com/opendistro/for-elasticsearch-docs/commit/2aecd4fd0162ac83573a8169ea734851bd871dad is sufficient and if you have any other thoughts.
