### ISSUE TITLE
Open distro security_kibana_plugin-0.9.0.0for  kibana 6.7.1 FATAL  Error: cluster 'security' already exists on start

### ISSUE THREAD

**Issue by akashhovale** [opendistro/for-elasticsearch-docs#80]
Hi,
I installed the Open distro security_kibana_plugin-0.9.0.0for  kibana 6.7.1 and on start of kibana I am getting below error(FATAL  Error: cluster 'security' already exists).Please guide 

log   [11:25:55.225] [info][status][plugin:opendistro_security@6.7.1] Status changed from yellow to green - Open Distro Security plugin version 6.7.1 initialised.
 log   [11:25:55.320] [info][status][plugin:metrics@6.7.1] Status changed from uninitialized to green - Ready
 log   [11:25:56.037] [info][status][plugin:timelion@6.7.1] Status changed from uninitialized to green - Ready
 log   [11:25:58.336] [error][status][plugin:xpack_main@6.7.1] Status changed from yellow to red - Authentication Exception
 log   [11:25:58.341] [error][status][plugin:spaces@6.7.1] Status changed from yellow to red - Authentication Exception
 log   [11:25:58.346] [error][status][plugin:searchprofiler@6.7.1] Status changed from yellow to red - Authentication Exception
 log   [11:25:58.353] [error][status][plugin:tilemap@6.7.1] Status changed from yellow to red - Authentication Exception
 log   [11:25:58.360] [error][status][plugin:grokdebugger@6.7.1] Status changed from yellow to red - Authentication Exception
 log   [11:25:58.366] [error][status][plugin:logstash@6.7.1] Status changed from yellow to red - Authentication Exception
 log   [11:25:58.370] [error][status][plugin:beats_management@6.7.1] Status changed from yellow to red - Authentication Exception
 log   [11:25:58.375] [error][status][plugin:maps@6.7.1] Status changed from yellow to red - Authentication Exception
 log   [11:25:58.380] [error][status][plugin:index_management@6.7.1] Status changed from yellow to red - Authentication Exception
 log   [11:25:58.385] [error][status][plugin:index_lifecycle_management@6.7.1] Status changed from yellow to red - Authentication Exception
 log   [11:25:58.388] [error][status][plugin:rollup@6.7.1] Status changed from yellow to red - Authentication Exception
 log   [11:25:58.393] [error][status][plugin:remote_clusters@6.7.1] Status changed from yellow to red - Authentication Exception
 log   [11:25:58.397] [error][status][plugin:cross_cluster_replication@6.7.1] Status changed from yellow to red - Authentication Exception
 log   [11:25:58.402] [error][status][plugin:elasticsearch@6.7.1] Status changed from yellow to red - Authentication Exception
 log   [11:25:58.425] [warning][license][xpack] License information from the X-Pack plugin could not be obtained from Elasticsearch for the [data] cluster. Authentication Exception :: {"path":"/_xpack","statusCode":401,"response":"Unauthorized","wwwAuthenticateDirective":"Basic realm=\"Open Distro Security\""}
 log   [11:25:59.983] [warning][reporting] Generating a random key for xpack.reporting.encryptionKey. To prevent pending reports from failing on restart, please set xpack.reporting.encryptionKey in kibana.yml
 log   [11:26:00.734] [error][status][plugin:reporting@6.7.1] Status changed from uninitialized to red - Authentication Exception
 log   [11:26:00.778] [fatal][root] Error: cluster 'security' already exists
   at Object.create [as createCluster] (D:\ELK\OPen_distro\kibana-6.7.1-windows-x86_64\src\legacy\core_plugins\elasticsearch\lib\create_clusters.js:29:15)
   at exports.getClient.server (D:/ELK/OPen_distro/kibana-6.7.1-windows-x86_64/node_modules/x-pack/server/lib/get_client_shield.js:15:48)
   at D:\ELK\OPen_distro\kibana-6.7.1-windows-x86_64\node_modules\lodash\index.js:7407:25
   at getUserFn (D:/ELK/OPen_distro/kibana-6.7.1-windows-x86_64/node_modules/x-pack/plugins/reporting/server/lib/get_user.js:11:33)
   at D:/ELK/OPen_distro/kibana-6.7.1-windows-x86_64/node_modules/x-pack/plugins/reporting/server/lib/once_per_server.js:30:15
   at memoized (D:\ELK\OPen_distro\kibana-6.7.1-windows-x86_64\node_modules\lodash\index.js:7956:27)
   at authorizedUserPreRoutingFn (D:/ELK/OPen_distro/kibana-6.7.1-windows-x86_64/node_modules/x-pack/plugins/reporting/server/lib/authorized_user_pre_routing.js:14:19)
   at D:/ELK/OPen_distro/kibana-6.7.1-windows-x86_64/node_modules/x-pack/plugins/reporting/server/lib/once_per_server.js:30:15
   at memoized (D:\ELK\OPen_distro\kibana-6.7.1-windows-x86_64\node_modules\lodash\index.js:7956:27)
   at main (D:/ELK/OPen_distro/kibana-6.7.1-windows-x86_64/node_modules/x-pack/plugins/reporting/server/routes/main.js:25:36)
   at Plugin.init [as externalInit] (D:/ELK/OPen_distro/kibana-6.7.1-windows-x86_64/node_modules/x-pack/plugins/reporting/index.js:178:7)
   at process._tickCallback (internal/process/next_tick.js:68:7)

FATAL  Error: cluster 'security' already exists

**Comment by aetter** [comment]
Hi @akashhovale, it looks like you're running the "default" distribution of Elasticsearch (which has a proprietary license and features like spaces and index management) rather than the OSS version. You might be able to get the Security plugin working on the default distribution by disabling some/all of the added features, but it's not a configuration that we test. If you try the OSS version, I think you'll have better luck.

**Comment by Arbuzov** [comment]
I use docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.2 and getting the same result
