### ISSUE TITLE
Minor error in Debian Installation docs

### ISSUE THREAD

**Issue by rahulk11501** [opendistro/for-elasticsearch-docs#81]
For the documentation:
https://opendistro.github.io/for-elasticsearch-docs/docs/install/deb/

Following lines perhaps need correction:

1. > These steps assume you’re using Ubuntu 18.04.

2.  > curl -XGET https://localhost:9200 -u admin:admin --insecure
     > curl -XGET https://localhost:9200/_cat/nodes?v -u admin:admin --insecure
     > curl -XGET https://localhost:9200/_cat/plugins?v -u admin:admin --insecure

Suggested Corrections:

1. > These steps assume you’re using Ubuntu 18.04 or 16.04.

2.  > curl -XGET http://localhost:9200 -u admin:admin --insecure
     > curl -XGET http://localhost:9200/_cat/nodes?v -u admin:admin --insecure
     > curl -XGET http://localhost:9200/_cat/plugins?v -u admin:admin --insecure

**Comment by aetter** [comment]
Hi @rahulk11501, although 16.04 should work fine and is one of our recommendations, I only test on 18.04, so I'm more comfortable leaving that line alone. For the other lines, no, the commands definitely need to include `https` in order to work with the security plugin. From an Ubuntu 18.04 machine:

```bash
$ curl -XGET http://localhost:9200 -u admin:admin --insecure
curl: (52) Empty reply from server

$ curl -XGET https://localhost:9200 -u admin:admin --insecure
{
  "name" : "dxvLEn2",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "DfutaQ8MTuCSeds84RJOfw",
  "version" : {
    "number" : "6.7.1",
    "build_flavor" : "oss",
    "build_type" : "deb",
    "build_hash" : "2f32220",
    "build_date" : "2019-04-02T15:59:27.961366Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by vanor89** [comment]
How would one be able to disable the security? I want to be able to hit http for local development but am having a hard time, even when setting `opendistro_security.ssl.http.enabled: 'true' `

**Comment by aetter** [comment]
Hi @vanor89, see this page for how to disable security: https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/disable/

If you don't want the Security plugin, another option is to start with elasticsearch-oss and only install the plugins you need: https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/
