### ISSUE TITLE
Error while installing KIbana

### ISSUE THREAD

**Issue by rahulk11501** [opendistro/for-elasticsearch-docs#82]
I am installing elastic-search and kibana using opendistro documentation.

I was able to install elastic search, but I am not able to install kiabana by following the documention
https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/

Command used - 

> sudo apt install opendistroforelasticsearch-kibana

Error log:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
W: Target DEP-11 (main/dep11/Components-all.yml) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
W: Target DEP-11-icons-small (main/dep11/icons-48x48.tar) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:52 and /etc/apt/sources.list.d/vscode.list:3
E: Unable to locate package opendistroforelasticsearch-kibana

**Comment by aetter** [comment]
Hi @rahulk11501, that error typically means you didn't add the repositories. I'm not able to reproduce on a fresh Ubuntu 18.04 machine. Can you run steps 2-3 [here](https://opendistro.github.io/for-elasticsearch-docs/docs/install/deb/) and then try again? If that doesn't do the trick, can you run `lsb_release -a` and post the output?

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```
