### ISSUE TITLE
The email notification from kibana through Amazon SNS does not show Message subject as mentioned.

### ISSUE THREAD

**Issue by bramu-rythmos** [opendistro/for-elasticsearch-docs#86]
Hello,
I included some subject in the message subject filed but while I am getting notified I see the subject as AWS Notification message instead of the subject I mentioned.

**Comment by aetter** [comment]
Hi @bramu-rythmos, thanks for reporting. This is a known issue with alerting on AES, and the team is working on a fix.

**Comment by bramu-rythmos** [comment]
Hello Team,

When can I expect the resolution on this.?



Thanks & Regards,
Basaveswar Rao Ramu,
Associate Consultant,
Rythmos India Private Limited.
________________________________
