### ISSUE TITLE
Alerts on kibana.

### ISSUE THREAD

**Issue by bramu-rythmos** [opendistro/for-elasticsearch-docs#88]
Hello Team, 
I have configured an alert for container restarts using extraction query. It matches certain phrase in message and trigger an alert. Now I have multiple containers in one instance. When the restart happen it only gives alert for only one container. Its not giving multiple alerts for different containers if the log is in same time period.

**Comment by aetter** [comment]
Hi @bramu-rythmos, unfortunately, this behavior is as-designed. If the query matches during the same period, it's considered part of the same alert. You can create a separate alarm for each container or just use the alert to say, "At least one container has entered alert status. Check the log for more information." You should also be able to include `ctx.results[0]` for more context.
