### ISSUE TITLE
Add cat API reference to Elasticsearch section

### ISSUE THREAD

**Issue by aetter** [opendistro/for-elasticsearch-docs#89]
Add reference page for all `_cat` APIs, similar to https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/full-text/

**Comment by oddlittlebird** [comment]
Where is the source content for this? Searching in either repo did not seem to show me anything useful.

(Disclaimer: I am an API noob, so please be patient I am missing something obvious.)

**Comment by aetter** [comment]
Hi @oddlittlebird, all content is in the `docs` directory of this repository. If you run `_cat` on a running cluster, you'll get a list of all available URIs:

```bash
$ curl -XGET https://localhost:9200/_cat -u admin:admin -k
=^.^=
/_cat/allocation
/_cat/shards
/_cat/shards/{index}
/_cat/master
/_cat/nodes
/_cat/tasks
/_cat/indices
/_cat/indices/{index}
/_cat/segments
/_cat/segments/{index}
/_cat/count
/_cat/count/{index}
/_cat/recovery
/_cat/recovery/{index}
/_cat/health
/_cat/pending_tasks
/_cat/aliases
/_cat/aliases/{alias}
/_cat/thread_pool
/_cat/thread_pool/{thread_pools}
/_cat/plugins
/_cat/fielddata
/_cat/fielddata/{fields}
/_cat/nodeattrs
/_cat/repositories
/_cat/snapshots/{repository}
/_cat/templates
```

`_cat` also has some global options that apply to all URIs.

**Comment by oddlittlebird** [comment]
Awesome, thanks. I will probably have more questions later, but that will get me started.

**Comment by oddlittlebird** [comment]
@aetter - I forked the repository and I am almost ready to merge my changes back in. It looks like I should create a pull request from my forked repository. Is that correct? The change is two new markdown documents.

**Comment by oddlittlebird** [comment]
@aashwinkumar12345 - If you are working on this issue, you might want to take a look at what I added.
