### ISSUE TITLE
Add documentation for OpenID connect

### ISSUE THREAD

**Issue by elfisher** [opendistro/for-elasticsearch-docs#9]
Moving from @kfox1111 [request](https://github.com/opendistro-for-elasticsearch/community/issues/14) Request below:

The documentation mentions JWT support, but it is unclear if it is enough to work with OIDC providers and only additional documentation is needed, or if OIDC support would require additional support. Either way, OIDC support would be very useful.

**Comment by aetter** [comment]
Hi @kfox1111 and @PPACI, I've added some OpenID Connect content, but frankly, it's untested. If you have an environment handy and can run through the configuration and offer feedback/a PR, it'd be a huge help. If not, no sweat of course. Thanks for reporting, and closing out! https://opendistro.github.io/for-elasticsearch-docs/docs/security/openid-connect/

**Comment by kfox1111** [comment]
Might take me a little while to find time to kick the tires. But I did a quick read through and looks very good. Thanks. :)
