### ISSUE TITLE
docker container not working : any documentation pointer ?

### ISSUE THREAD

**Issue by christopheblin** [opendistro/for-elasticsearch-docs#95]
I'm on Mac OS, with docker desktop and kitematic

I've downloaded the amazon/opendistro-for-elasticsearch:1.0.0 and then when the container starts, it stops just after 

    ### To access your secured cluster open https://<hostname>:<HTTP port> and log in with admin/admin.
    ### (Ignore the SSL certificate warning because we installed self-signed demo certificates)
    OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

But then, obviously, nothing works :

```
$ curl -XGET https://localhost:9200 -u admin:admin --insecure
curl: (7) Failed to connect to localhost port 9200: Connection refused
```

I've also tried to remove the container and follow doc at https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/ and to run `docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" amazon/opendistro-for-elasticsearch:1.0.0` but it also stops at the same place

Is there a documentation to troubleshot that ? Like common pitfalls, etc...

**Comment by christopheblin** [comment]
Ok I've found it myself

The problem was that I restricted the memory usage of docker too much for the container (that can not start under 2GB of RAM allowed to the docker)

Would be great to mention that somewhere in the documnetaion though ...

**Comment by aetter** [comment]
Hi @christopheblin, glad you were able to get to the bottom of it. Memory in Docker often leads to some odd behavior, which is why we recommend allocated at least 4GB here: https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/#sample-docker-compose-file
