### ISSUE TITLE
Problem with installing opendistroforelasticsearch 6.7.1

### ISSUE THREAD

**Issue by rnkhouse** [opendistro/for-elasticsearch-docs#99]
I am running this version `6.7.1` in elasticsearch OSS using this guide:
https://opendistro.github.io/for-elasticsearch-docs/docs/install/deb/

    wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.7.1-amd64.deb
    sudo dpkg -i elasticsearch-oss-6.7.1-amd64.deb
    sudo apt-get update
    sudo apt install opendistroforelasticsearch

Error:

>Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

>The following packages have unmet dependencies:
 opendistroforelasticsearch : Depends: elasticsearch-oss (= 7.0.1) but 6.7.1 is to be installed
                              Depends: opendistro-alerting (>= 1.0.0) but it is not going to be installed
                              Depends: opendistro-sql (>= 1.0.0) but it is not going to be installed
                              Depends: opendistro-security (>= 1.0.0) but it is not going to be installed
                              Depends: opendistro-performance-analyzer (>= 1.0.0) but it is not going to be installed
                              Depends: opendistro-job-scheduler (>= 1.0.0) but it is not going to be installed
                              Depends: opendistro-alerting (< 1.0.1) but it is not going to be installed
                              Depends: opendistro-sql (< 1.0.1) but it is not going to be installed
                              Depends: opendistro-security (< 1.0.1) but it is not going to be installed
                              Depends: opendistro-performance-analyzer (< 1.0.1) but it is not going to be installed
                              Depends: opendistro-job-scheduler (< 1.0.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

It was working fine before. Suddenly it stopped working!
How can I install the older version which is `0.9.0`

**Comment by aetter** [comment]
Hi @rnkhouse, this is a known issue with apt. Apt always tries to upgrade dependencies to their latest versions, rather than yum, which lets you lock dependencies for a given version. So if you're installing something fresh out of the box, the only easy way is to jump to the latest version. The harder way is to manually install all dependencies first, like this:

```
$ sudo apt install opendistroforelasticsearch=0.9.0-1 -V
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 opendistroforelasticsearch : Depends: opendistro-alerting (>= 0.9.0) but it is not going to be installed
                              Depends: opendistro-sql (>= 0.9.0) but it is not going to be installed
                              Depends: opendistro-security (>= 0.9.0) but it is not going to be installed
                              Depends: opendistro-performance-analyzer (>= 0.9.0) but it is not going to be installed
                              Depends: opendistro-alerting (< 0.9.1) but it is not going to be installed
                              Depends: opendistro-sql (< 0.9.1) but it is not going to be installed
                              Depends: opendistro-security (< 0.9.1) but it is not going to be installed
                              Depends: opendistro-performance-analyzer (< 0.9.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

$ sudo apt install opendistro-alerting=0.9.0.0-1 -V
$ sudo apt install opendistro-sql=0.9.0.0-1 -V
$ sudo apt install opendistro-security=0.9.0.0-0 -V
$ sudo apt install opendistro-performance-analyzer=0.9.0.0-1 -V
$ sudo apt install opendistroforelasticsearch=0.9.0-1 -V
```

Pretty sure you'll have to manually upgrade all plugin package during upgrade, as well.

**Comment by rnkhouse** [comment]
Alright!
How about for kibana?

apt install opendistroforelasticsearch-kibana=0.9.0-1 -V
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '0.9.0-1' for 'opendistroforelasticsearch-kibana' was not found

**Comment by aetter** [comment]
Hi @rnkhouse, same process, though I'm not sure if you'll need to install the [Kibana plugins](https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/plugins/) manually.

For whatever reason, all the plugins/projects use slightly different versioning. You can get all the versions for a given package like so:

```
$ $ apt list -a opendistroforelasticsearch-kibana
Listing... Done
opendistroforelasticsearch-kibana/stable 1.0.1 amd64
opendistroforelasticsearch-kibana/stable 1.0.0 amd64
opendistroforelasticsearch-kibana/stable 0.9.0 amd64
opendistroforelasticsearch-kibana/stable 0.8.0 amd64

$ sudo apt install opendistroforelasticsearch-kibana=0.9.0 -V
```
